2025-04-09 18:10:07,471-__main__-INFO-Starting data ingestion process....
2025-04-09 18:10:07,471-src.exception-ERROR-Error Message: module 'tabulate' has no attribute 'read_pdf'
2025-04-09 18:10:07,474-src.exception-ERROR-Error Details: (<class 'AttributeError'>, AttributeError("module 'tabulate' has no attribute 'read_pdf'"), <traceback object at 0x10425af40>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/data_ingestion.py", line 27, in initiate_data_ingestion
    df = tabulate.read_pdf(self.data_ingestion_config.raw_data_path,pages='all',multiple_tables=False)
AttributeError: module 'tabulate' has no attribute 'read_pdf'

2025-04-09 18:13:47,738-__main__-INFO-Starting data ingestion process....
2025-04-09 18:13:47,740-tabula.backend-WARNING-Failed to import jpype dependencies. Fallback to subprocess.
2025-04-09 18:13:47,741-tabula.backend-WARNING-No module named 'jpype'
2025-04-09 18:15:23,984-src.exception-ERROR-Error Message: 'list' object has no attribute 'to_csv'
2025-04-09 18:15:23,990-src.exception-ERROR-Error Details: (<class 'AttributeError'>, AttributeError("'list' object has no attribute 'to_csv'"), <traceback object at 0x122926780>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/data_ingestion.py", line 33, in initiate_data_ingestion
AttributeError: 'list' object has no attribute 'to_csv'

2025-04-09 18:17:51,456-__main__-INFO-Starting data ingestion process....
2025-04-09 18:17:51,458-tabula.backend-WARNING-Failed to import jpype dependencies. Fallback to subprocess.
2025-04-09 18:17:51,460-tabula.backend-WARNING-No module named 'jpype'
2025-04-09 18:17:52,203-tabula.backend-ERROR-Error from tabula-java:
Error: Cannot create file artifacts/raw/olfc_data.csv


2025-04-09 18:17:52,204-src.exception-ERROR-Error Message: Command '['java', '-Djava.awt.headless=true', '-Dfile.encoding=UTF8', '-jar', '/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/tabula/tabula-1.0.5-jar-with-dependencies.jar', '--pages', 'all', '--guess', '--format', 'CSV', '--outfile', 'artifacts/raw/olfc_data.csv', 'data/raw/olfc_data.pdf']' returned non-zero exit status 1.
2025-04-09 18:17:52,333-src.exception-ERROR-Error Details: (<class 'subprocess.CalledProcessError'>, CalledProcessError(1, ['java', '-Djava.awt.headless=true', '-Dfile.encoding=UTF8', '-jar', '/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/tabula/tabula-1.0.5-jar-with-dependencies.jar', '--pages', 'all', '--guess', '--format', 'CSV', '--outfile', 'artifacts/raw/olfc_data.csv', 'data/raw/olfc_data.pdf']), <traceback object at 0x12416d740>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/data_ingestion.py", line 27, in initiate_data_ingestion
    tabula.convert_into(self.data_ingestion_config.raw_data_path,self.data_ingestion_config.data_path,pages="all",output_format="csv")
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/tabula/io.py", line 835, in convert_into
    _run(tabula_options, java_options, path, force_subprocess=force_subprocess)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/tabula/io.py", line 86, in _run
    return _tabula_vm.call_tabula_java(options, path)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/tabula/backend.py", line 122, in call_tabula_java
    result = subprocess.run(
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['java', '-Djava.awt.headless=true', '-Dfile.encoding=UTF8', '-jar', '/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/tabula/tabula-1.0.5-jar-with-dependencies.jar', '--pages', 'all', '--guess', '--format', 'CSV', '--outfile', 'artifacts/raw/olfc_data.csv', 'data/raw/olfc_data.pdf']' returned non-zero exit status 1.

2025-04-09 18:19:24,743-__main__-INFO-Starting data ingestion process....
2025-04-09 18:19:24,744-tabula.backend-WARNING-Failed to import jpype dependencies. Fallback to subprocess.
2025-04-09 18:19:24,745-tabula.backend-WARNING-No module named 'jpype'
2025-04-09 18:22:06,880-__main__-INFO-Starting data ingestion process....
2025-04-09 18:24:20,260-__main__-INFO-Data saved to CSV at: artifacts/raw/olfc_data.csv
2025-04-09 18:24:20,264-__main__-INFO-Data Ingestion Completed
2025-04-09 19:42:34,456-__main__-INFO-Starting data ingestion process....
2025-04-09 19:43:56,660-src.exception-ERROR-Error Message: org.apache.commons.cli.ParseException: Cannot create file artifacts/dataset/olfc_data.csv
2025-04-09 19:43:56,676-src.exception-ERROR-Error Details: (<java class 'org.apache.commons.cli.ParseException'>, ParseException('Cannot create file artifacts/dataset/olfc_data.csv'), <traceback object at 0x14e1802c0>)Traceback (most recent call last):
  File "CommandLineApp.java", line 106, in technology.tabula.CommandLineApp.extractTables
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/1_data_ingestion.py", line 28, in initiate_data_ingestion
    tabula.convert_into(self.data_ingestion_config.raw_data_path,self.data_ingestion_config.data_path,pages="all",output_format="csv")
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/tabula/io.py", line 835, in convert_into
    _run(tabula_options, java_options, path, force_subprocess=force_subprocess)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/tabula/io.py", line 86, in _run
    return _tabula_vm.call_tabula_java(options, path)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/tabula/backend.py", line 73, in call_tabula_java
    self.tabula.CommandLineApp(sb, cmd).extractTables(cmd)
org.apache.commons.cli.org.apache.commons.cli.ParseException: org.apache.commons.cli.ParseException: Cannot create file artifacts/dataset/olfc_data.csv

2025-04-09 19:44:17,984-__main__-INFO-Starting data ingestion process....
2025-04-09 19:47:43,902-__main__-INFO-Data saved to CSV at: artifacts/dataset/olfc_data.csv
2025-04-09 19:47:43,908-__main__-INFO-Data Ingestion Completed
2025-04-09 20:10:49,110-__main__-INFO-EDA processing initialising......
2025-04-09 20:10:49,111-__main__-INFO-Loading data from: artifacts/dataset/olfc_data.csv
2025-04-09 20:10:49,371-__main__-INFO-Data loaded successfully loaded
2025-04-09 20:10:49,371-__main__-INFO-Generating the EDA Summary
2025-04-09 20:10:49,372-__main__-INFO-Data Shape: (25480, 12)
2025-04-09 20:10:49,424-__main__-INFO-Data Info: None
2025-04-09 20:10:49,474-__main__-INFO-Data Describe:        ninog_of_employee  ...  pmrevnat iling_wage
count       25480.000000  ...         25480.000000
mean         5667.043210  ...         74455.814592
std         22877.928848  ...         52815.942327
min           -26.000000  ...             2.136700
25%          1022.000000  ...         34015.480000
50%          2109.000000  ...         70308.210000
75%          3504.000000  ...        107735.512500
max        602069.000000  ...        319210.270000

[8 rows x 3 columns]
2025-04-09 20:10:49,488-__main__-INFO-Missing Values: 
case_id                  0
continent                0
education_of_e           0
phlaosy_ejeob_experie    0
rceequires_job_trai      0
ninog_of_employee        0
yr_of_estab              0
region_of_emplo          0
pmrevnat iling_wage      0
unit_of_wage             0
full_time_positio        0
case_status              0
dtype: int64
2025-04-09 20:10:49,550-__main__-INFO-EDA Summary saved to: artifacts/eda/eda_report.pdf
2025-04-09 20:10:49,552-__main__-INFO-EDA Process Completed
2025-04-09 20:13:59,551-__main__-INFO-EDA processing initialising......
2025-04-09 20:13:59,552-__main__-INFO-Loading data from: artifacts/dataset/olfc_data.csv
2025-04-09 20:13:59,671-__main__-INFO-Data loaded successfully loaded
2025-04-09 20:13:59,672-__main__-INFO-Generating the EDA Summary
2025-04-09 20:13:59,672-__main__-INFO-Data Shape: (25480, 12)
2025-04-09 20:13:59,727-__main__-INFO-Data Info: None
2025-04-09 20:13:59,830-__main__-INFO-Data Describe:        ninog_of_employee   yr_of_estab  pmrevnat iling_wage
count       25480.000000  25480.000000         25480.000000
mean         5667.043210   1979.409929         74455.814592
std         22877.928848     42.366929         52815.942327
min           -26.000000   1800.000000             2.136700
25%          1022.000000   1976.000000         34015.480000
50%          2109.000000   1997.000000         70308.210000
75%          3504.000000   2005.000000        107735.512500
max        602069.000000   2016.000000        319210.270000
2025-04-09 20:13:59,845-__main__-INFO-Missing Values: 
case_id                  0
continent                0
education_of_e           0
phlaosy_ejeob_experie    0
rceequires_job_trai      0
ninog_of_employee        0
yr_of_estab              0
region_of_emplo          0
pmrevnat iling_wage      0
unit_of_wage             0
full_time_positio        0
case_status              0
dtype: int64
2025-04-09 20:13:59,903-__main__-INFO-EDA Summary saved to: artifacts/eda/eda_report.pdf
2025-04-09 20:13:59,904-__main__-INFO-EDA Process Completed
2025-04-09 20:14:46,923-__main__-INFO-EDA processing initialising......
2025-04-09 20:14:46,924-__main__-INFO-Loading data from: artifacts/dataset/olfc_data.csv
2025-04-09 20:14:47,033-__main__-INFO-Data loaded successfully loaded
2025-04-09 20:14:47,033-__main__-INFO-Generating the EDA Summary
2025-04-09 20:14:47,034-__main__-INFO-Data Shape: (25480, 12)
2025-04-09 20:14:47,091-__main__-INFO-Data Info: None
2025-04-09 20:14:47,131-__main__-INFO-Data Describe:        ninog_of_employee  ...  pmrevnat iling_wage
count       25480.000000  ...         25480.000000
mean         5667.043210  ...         74455.814592
std         22877.928848  ...         52815.942327
min           -26.000000  ...             2.136700
25%          1022.000000  ...         34015.480000
50%          2109.000000  ...         70308.210000
75%          3504.000000  ...        107735.512500
max        602069.000000  ...        319210.270000

[8 rows x 3 columns]
2025-04-09 20:14:47,146-__main__-INFO-Missing Values: 
case_id                  0
continent                0
education_of_e           0
phlaosy_ejeob_experie    0
rceequires_job_trai      0
ninog_of_employee        0
yr_of_estab              0
region_of_emplo          0
pmrevnat iling_wage      0
unit_of_wage             0
full_time_positio        0
case_status              0
dtype: int64
2025-04-09 20:14:47,204-__main__-INFO-EDA Summary saved to: artifacts/eda/eda_report.pdf
2025-04-09 20:14:47,205-__main__-INFO-EDA Process Completed
2025-04-09 20:19:36,511-__main__-INFO-EDA processing initialising......
2025-04-09 20:19:36,512-__main__-INFO-Loading data from: artifacts/dataset/olfc_data.csv
2025-04-09 20:19:36,616-__main__-INFO-Data loaded successfully loaded
2025-04-09 20:19:36,656-__main__-INFO-Generating the EDA Summary
2025-04-09 20:19:36,656-__main__-INFO-Data Shape: (25480, 12)
2025-04-09 20:19:36,656-__main__-INFO-Data Info: <class 'pandas.core.frame.DataFrame'>
RangeIndex: 25480 entries, 0 to 25479
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   case_id                25480 non-null  object 
 1   continent              25480 non-null  object 
 2   education_of_e         25480 non-null  object 
 3   phlaosy_ejeob_experie  25480 non-null  object 
 4   rceequires_job_trai    25480 non-null  object 
 5   ninog_of_employee      25480 non-null  int64  
 6   yr_of_estab            25480 non-null  int64  
 7   region_of_emplo        25480 non-null  object 
 8   pmrevnat iling_wage    25480 non-null  float64
 9   unit_of_wage           25480 non-null  object 
 10  full_time_positio      25480 non-null  object 
 11  case_status            25480 non-null  object 
dtypes: float64(1), int64(2), object(9)
memory usage: 2.3+ MB

2025-04-09 20:19:36,710-__main__-INFO-Data Describe:        ninog_of_employee   yr_of_estab  pmrevnat iling_wage
count       25480.000000  25480.000000         25480.000000
mean         5667.043210   1979.409929         74455.814592
std         22877.928848     42.366929         52815.942327
min           -26.000000   1800.000000             2.136700
25%          1022.000000   1976.000000         34015.480000
50%          2109.000000   1997.000000         70308.210000
75%          3504.000000   2005.000000        107735.512500
max        602069.000000   2016.000000        319210.270000
2025-04-09 20:19:36,727-__main__-INFO-Missing Values: 
case_id                  0
continent                0
education_of_e           0
phlaosy_ejeob_experie    0
rceequires_job_trai      0
ninog_of_employee        0
yr_of_estab              0
region_of_emplo          0
pmrevnat iling_wage      0
unit_of_wage             0
full_time_positio        0
case_status              0
dtype: int64
2025-04-09 20:19:36,784-__main__-INFO-EDA Summary saved to: artifacts/eda/eda_report.pdf
2025-04-09 20:19:36,786-__main__-INFO-EDA Process Completed
2025-04-09 20:26:00,805-__main__-INFO-EDA processing initialising......
2025-04-09 20:26:00,806-__main__-INFO-Loading data from: artifacts/dataset/olfc_data.csv
2025-04-09 20:26:01,158-__main__-INFO-Data loaded successfully loaded
2025-04-09 20:26:01,197-__main__-INFO-Generating the EDA Summary
2025-04-09 20:26:01,250-__main__-INFO-Data Head:   case_id continent  ... full_time_positio case_status
0  EZYV01      Asia  ...                 Y      Denied
1  EZYV02      Asia  ...                 Y   Certified
2  EZYV03      Asia  ...                 Y      Denied
3  EZYV04      Asia  ...                 Y      Denied
4  EZYV05    Africa  ...                 Y   Certified

[5 rows x 12 columns]
2025-04-09 20:26:01,250-__main__-INFO-Data Shape: (25480, 12)
2025-04-09 20:26:01,251-__main__-INFO-Data Info: <class 'pandas.core.frame.DataFrame'>
RangeIndex: 25480 entries, 0 to 25479
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   case_id                25480 non-null  object 
 1   continent              25480 non-null  object 
 2   education_of_e         25480 non-null  object 
 3   phlaosy_ejeob_experie  25480 non-null  object 
 4   rceequires_job_trai    25480 non-null  object 
 5   ninog_of_employee      25480 non-null  int64  
 6   yr_of_estab            25480 non-null  int64  
 7   region_of_emplo        25480 non-null  object 
 8   pmrevnat iling_wage    25480 non-null  float64
 9   unit_of_wage           25480 non-null  object 
 10  full_time_positio      25480 non-null  object 
 11  case_status            25480 non-null  object 
dtypes: float64(1), int64(2), object(9)
memory usage: 2.3+ MB

2025-04-09 20:26:01,311-__main__-INFO-Data Describe:        ninog_of_employee   yr_of_estab  pmrevnat iling_wage
count       25480.000000  25480.000000         25480.000000
mean         5667.043210   1979.409929         74455.814592
std         22877.928848     42.366929         52815.942327
min           -26.000000   1800.000000             2.136700
25%          1022.000000   1976.000000         34015.480000
50%          2109.000000   1997.000000         70308.210000
75%          3504.000000   2005.000000        107735.512500
max        602069.000000   2016.000000        319210.270000
2025-04-09 20:26:01,351-__main__-INFO-Duplicated Values: 0
2025-04-09 20:26:01,367-__main__-INFO-Missing Values: 
case_id                  0
continent                0
education_of_e           0
phlaosy_ejeob_experie    0
rceequires_job_trai      0
ninog_of_employee        0
yr_of_estab              0
region_of_emplo          0
pmrevnat iling_wage      0
unit_of_wage             0
full_time_positio        0
case_status              0
dtype: int64
2025-04-09 20:26:01,401-__main__-INFO-Unique Values: 
case_id                  25480
continent                    6
education_of_e               4
phlaosy_ejeob_experie        2
rceequires_job_trai          2
ninog_of_employee         7105
yr_of_estab                199
region_of_emplo              5
pmrevnat iling_wage      25454
unit_of_wage                 4
full_time_positio            2
case_status                  2
dtype: int64
2025-04-09 20:26:01,578-__main__-INFO-EDA Summary saved to: artifacts/eda/eda_report.pdf
2025-04-09 20:26:01,581-__main__-INFO-EDA Process Completed
2025-04-09 20:31:09,394-__main__-INFO-EDA processing initialising......
2025-04-09 20:31:09,395-__main__-INFO-Loading data from: artifacts/dataset/olfc_data.csv
2025-04-09 20:31:09,504-__main__-INFO-Data loaded successfully loaded
2025-04-09 20:31:09,544-__main__-INFO-Generating the EDA Summary
2025-04-09 20:31:09,583-__main__-INFO-Data Head:   case_id continent  ... full_time_positio case_status
0  EZYV01      Asia  ...                 Y      Denied
1  EZYV02      Asia  ...                 Y   Certified
2  EZYV03      Asia  ...                 Y      Denied
3  EZYV04      Asia  ...                 Y      Denied
4  EZYV05    Africa  ...                 Y   Certified

[5 rows x 12 columns]
2025-04-09 20:31:09,583-__main__-INFO-Data Shape: (25480, 12)
2025-04-09 20:31:09,583-__main__-INFO-Data Info: <class 'pandas.core.frame.DataFrame'>
RangeIndex: 25480 entries, 0 to 25479
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   case_id                25480 non-null  object 
 1   continent              25480 non-null  object 
 2   education_of_e         25480 non-null  object 
 3   phlaosy_ejeob_experie  25480 non-null  object 
 4   rceequires_job_trai    25480 non-null  object 
 5   ninog_of_employee      25480 non-null  int64  
 6   yr_of_estab            25480 non-null  int64  
 7   region_of_emplo        25480 non-null  object 
 8   pmrevnat iling_wage    25480 non-null  float64
 9   unit_of_wage           25480 non-null  object 
 10  full_time_positio      25480 non-null  object 
 11  case_status            25480 non-null  object 
dtypes: float64(1), int64(2), object(9)
memory usage: 2.3+ MB

2025-04-09 20:31:09,616-__main__-INFO-Data Describe:        ninog_of_employee   yr_of_estab  pmrevnat iling_wage
count       25480.000000  25480.000000         25480.000000
mean         5667.043210   1979.409929         74455.814592
std         22877.928848     42.366929         52815.942327
min           -26.000000   1800.000000             2.136700
25%          1022.000000   1976.000000         34015.480000
50%          2109.000000   1997.000000         70308.210000
75%          3504.000000   2005.000000        107735.512500
max        602069.000000   2016.000000        319210.270000
2025-04-09 20:31:09,641-__main__-INFO-Duplicated Values: 0
2025-04-09 20:31:09,658-__main__-INFO-Missing Values: 
case_id                  0
continent                0
education_of_e           0
phlaosy_ejeob_experie    0
rceequires_job_trai      0
ninog_of_employee        0
yr_of_estab              0
region_of_emplo          0
pmrevnat iling_wage      0
unit_of_wage             0
full_time_positio        0
case_status              0
dtype: int64
2025-04-09 20:31:09,687-__main__-INFO-Unique Values: 
case_id                  25480
continent                    6
education_of_e               4
phlaosy_ejeob_experie        2
rceequires_job_trai          2
ninog_of_employee         7105
yr_of_estab                199
region_of_emplo              5
pmrevnat iling_wage      25454
unit_of_wage                 4
full_time_positio            2
case_status                  2
dtype: int64
2025-04-09 20:31:09,783-__main__-INFO-EDA Summary saved to: artifacts/eda/eda_report
2025-04-09 20:31:09,786-__main__-INFO-EDA Process Completed
2025-04-10 09:50:17,526-__main__-INFO-EDA processing initialising......
2025-04-10 09:50:17,527-__main__-INFO-Loading data from: artifacts/dataset/olfc_data.csv
2025-04-10 09:50:17,633-__main__-INFO-Data loaded successfully loaded
2025-04-10 09:50:17,668-__main__-INFO-Generating the EDA Summary
2025-04-10 09:50:17,702-__main__-INFO-Data Head:   case_id continent  ... full_time_positio case_status
0  EZYV01      Asia  ...                 Y      Denied
1  EZYV02      Asia  ...                 Y   Certified
2  EZYV03      Asia  ...                 Y      Denied
3  EZYV04      Asia  ...                 Y      Denied
4  EZYV05    Africa  ...                 Y   Certified

[5 rows x 12 columns]
2025-04-10 09:50:17,702-__main__-INFO-Data Shape: (25480, 12)
2025-04-10 09:50:17,702-__main__-INFO-Data Info: <class 'pandas.core.frame.DataFrame'>
RangeIndex: 25480 entries, 0 to 25479
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   case_id                25480 non-null  object 
 1   continent              25480 non-null  object 
 2   education_of_e         25480 non-null  object 
 3   phlaosy_ejeob_experie  25480 non-null  object 
 4   rceequires_job_trai    25480 non-null  object 
 5   ninog_of_employee      25480 non-null  int64  
 6   yr_of_estab            25480 non-null  int64  
 7   region_of_emplo        25480 non-null  object 
 8   pmrevnat iling_wage    25480 non-null  float64
 9   unit_of_wage           25480 non-null  object 
 10  full_time_positio      25480 non-null  object 
 11  case_status            25480 non-null  object 
dtypes: float64(1), int64(2), object(9)
memory usage: 2.3+ MB

2025-04-10 09:50:17,738-__main__-INFO-Data Describe:        ninog_of_employee   yr_of_estab  pmrevnat iling_wage
count       25480.000000  25480.000000         25480.000000
mean         5667.043210   1979.409929         74455.814592
std         22877.928848     42.366929         52815.942327
min           -26.000000   1800.000000             2.136700
25%          1022.000000   1976.000000         34015.480000
50%          2109.000000   1997.000000         70308.210000
75%          3504.000000   2005.000000        107735.512500
max        602069.000000   2016.000000        319210.270000
2025-04-10 09:50:17,765-__main__-INFO-Duplicated Values: 0
2025-04-10 09:50:17,777-__main__-INFO-Missing Values: 
case_id                  0
continent                0
education_of_e           0
phlaosy_ejeob_experie    0
rceequires_job_trai      0
ninog_of_employee        0
yr_of_estab              0
region_of_emplo          0
pmrevnat iling_wage      0
unit_of_wage             0
full_time_positio        0
case_status              0
dtype: int64
2025-04-10 09:50:17,809-__main__-INFO-Unique Values: 
case_id                  25480
continent                    6
education_of_e               4
phlaosy_ejeob_experie        2
rceequires_job_trai          2
ninog_of_employee         7105
yr_of_estab                199
region_of_emplo              5
pmrevnat iling_wage      25454
unit_of_wage                 4
full_time_positio            2
case_status                  2
dtype: int64
2025-04-10 09:50:17,811-__main__-INFO-Unique Values in Case Status: 
2
2025-04-10 09:50:17,909-__main__-INFO-EDA Summary saved to: artifacts/eda/eda_report
2025-04-10 09:50:17,911-__main__-INFO-EDA Process Completed
2025-04-10 09:51:44,376-__main__-INFO-EDA processing initialising......
2025-04-10 09:51:44,377-__main__-INFO-Loading data from: artifacts/dataset/olfc_data.csv
2025-04-10 09:51:44,502-__main__-INFO-Data loaded successfully loaded
2025-04-10 09:51:44,534-__main__-INFO-Generating the EDA Summary
2025-04-10 09:51:44,565-__main__-INFO-Data Head:   case_id continent  ... full_time_positio case_status
0  EZYV01      Asia  ...                 Y      Denied
1  EZYV02      Asia  ...                 Y   Certified
2  EZYV03      Asia  ...                 Y      Denied
3  EZYV04      Asia  ...                 Y      Denied
4  EZYV05    Africa  ...                 Y   Certified

[5 rows x 12 columns]
2025-04-10 09:51:44,566-__main__-INFO-Data Shape: (25480, 12)
2025-04-10 09:51:44,566-__main__-INFO-Data Info: <class 'pandas.core.frame.DataFrame'>
RangeIndex: 25480 entries, 0 to 25479
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   case_id                25480 non-null  object 
 1   continent              25480 non-null  object 
 2   education_of_e         25480 non-null  object 
 3   phlaosy_ejeob_experie  25480 non-null  object 
 4   rceequires_job_trai    25480 non-null  object 
 5   ninog_of_employee      25480 non-null  int64  
 6   yr_of_estab            25480 non-null  int64  
 7   region_of_emplo        25480 non-null  object 
 8   pmrevnat iling_wage    25480 non-null  float64
 9   unit_of_wage           25480 non-null  object 
 10  full_time_positio      25480 non-null  object 
 11  case_status            25480 non-null  object 
dtypes: float64(1), int64(2), object(9)
memory usage: 2.3+ MB

2025-04-10 09:51:44,600-__main__-INFO-Data Describe:        ninog_of_employee   yr_of_estab  pmrevnat iling_wage
count       25480.000000  25480.000000         25480.000000
mean         5667.043210   1979.409929         74455.814592
std         22877.928848     42.366929         52815.942327
min           -26.000000   1800.000000             2.136700
25%          1022.000000   1976.000000         34015.480000
50%          2109.000000   1997.000000         70308.210000
75%          3504.000000   2005.000000        107735.512500
max        602069.000000   2016.000000        319210.270000
2025-04-10 09:51:44,628-__main__-INFO-Duplicated Values: 0
2025-04-10 09:51:44,643-__main__-INFO-Missing Values: 
case_id                  0
continent                0
education_of_e           0
phlaosy_ejeob_experie    0
rceequires_job_trai      0
ninog_of_employee        0
yr_of_estab              0
region_of_emplo          0
pmrevnat iling_wage      0
unit_of_wage             0
full_time_positio        0
case_status              0
dtype: int64
2025-04-10 09:51:44,669-__main__-INFO-Unique Values: 
58265
2025-04-10 09:51:44,672-__main__-INFO-Unique Values in Case Status: 
2
2025-04-10 09:51:44,783-__main__-INFO-EDA Summary saved to: artifacts/eda/eda_report
2025-04-10 09:51:44,788-__main__-INFO-EDA Process Completed
2025-04-10 09:53:47,458-__main__-INFO-EDA processing initialising......
2025-04-10 09:53:47,460-__main__-INFO-Loading data from: artifacts/dataset/olfc_data.csv
2025-04-10 09:53:47,587-__main__-INFO-Data loaded successfully loaded
2025-04-10 09:53:47,623-__main__-INFO-Generating the EDA Summary
2025-04-10 09:53:47,655-__main__-INFO-Data Head:   case_id continent  ... full_time_positio case_status
0  EZYV01      Asia  ...                 Y      Denied
1  EZYV02      Asia  ...                 Y   Certified
2  EZYV03      Asia  ...                 Y      Denied
3  EZYV04      Asia  ...                 Y      Denied
4  EZYV05    Africa  ...                 Y   Certified

[5 rows x 12 columns]
2025-04-10 09:53:47,655-__main__-INFO-Data Shape: (25480, 12)
2025-04-10 09:53:47,655-__main__-INFO-Data Info: <class 'pandas.core.frame.DataFrame'>
RangeIndex: 25480 entries, 0 to 25479
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   case_id                25480 non-null  object 
 1   continent              25480 non-null  object 
 2   education_of_e         25480 non-null  object 
 3   phlaosy_ejeob_experie  25480 non-null  object 
 4   rceequires_job_trai    25480 non-null  object 
 5   ninog_of_employee      25480 non-null  int64  
 6   yr_of_estab            25480 non-null  int64  
 7   region_of_emplo        25480 non-null  object 
 8   pmrevnat iling_wage    25480 non-null  float64
 9   unit_of_wage           25480 non-null  object 
 10  full_time_positio      25480 non-null  object 
 11  case_status            25480 non-null  object 
dtypes: float64(1), int64(2), object(9)
memory usage: 2.3+ MB

2025-04-10 09:53:47,693-__main__-INFO-Data Describe:        ninog_of_employee   yr_of_estab  pmrevnat iling_wage
count       25480.000000  25480.000000         25480.000000
mean         5667.043210   1979.409929         74455.814592
std         22877.928848     42.366929         52815.942327
min           -26.000000   1800.000000             2.136700
25%          1022.000000   1976.000000         34015.480000
50%          2109.000000   1997.000000         70308.210000
75%          3504.000000   2005.000000        107735.512500
max        602069.000000   2016.000000        319210.270000
2025-04-10 09:53:47,720-__main__-INFO-Duplicated Values: 0
2025-04-10 09:53:47,735-__main__-INFO-Missing Values: 
case_id                  0
continent                0
education_of_e           0
phlaosy_ejeob_experie    0
rceequires_job_trai      0
ninog_of_employee        0
yr_of_estab              0
region_of_emplo          0
pmrevnat iling_wage      0
unit_of_wage             0
full_time_positio        0
case_status              0
dtype: int64
2025-04-10 09:53:47,760-__main__-INFO-Unique Values: 
case_id                  25480
continent                    6
education_of_e               4
phlaosy_ejeob_experie        2
rceequires_job_trai          2
ninog_of_employee         7105
yr_of_estab                199
region_of_emplo              5
pmrevnat iling_wage      25454
unit_of_wage                 4
full_time_positio            2
case_status                  2
dtype: int64
2025-04-10 09:53:47,764-__main__-INFO-Unique Values in Case Status: 
case_status
Certified    17018
Denied        8462
Name: count, dtype: int64
2025-04-10 09:53:47,873-__main__-INFO-EDA Summary saved to: artifacts/eda/eda_report
2025-04-10 09:53:47,875-__main__-INFO-EDA Process Completed
2025-04-10 14:34:18,046-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 14:34:18,220-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 14:34:18,232-src.exception-ERROR-Error Message: 'education_of_employee'
2025-04-10 14:34:18,347-src.exception-ERROR-Error Details: (<class 'KeyError'>, KeyError('education_of_employee'), <traceback object at 0x13240b740>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'education_of_employee'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 46, in initiate_feature_engineering
    df['education_of_employee'] = df['education_of_employee'].str.replace("’s", "", regex=False)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'education_of_employee'

2025-04-10 14:38:41,413-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 14:38:41,723-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 14:38:42,106-__main__-INFO-Preprocessing features
2025-04-10 14:38:42,412-__main__-INFO-Applying SMOTE for class balancing
2025-04-10 14:38:55,434-src.exception-ERROR-Error Message: Shape of passed values is (34036, 1), indices imply (34036, 25505)
2025-04-10 14:38:56,102-src.exception-ERROR-Error Details: (<class 'ValueError'>, ValueError('Shape of passed values is (34036, 1), indices imply (34036, 25505)'), <traceback object at 0x136a388c0>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 107, in initiate_feature_engineering
    X_df = pd.DataFrame(X_balanced, columns=feature_names)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/core/frame.py", line 867, in __init__
    mgr = ndarray_to_mgr(
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 336, in ndarray_to_mgr
    _check_values_indices_shape_match(values, index, columns)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 420, in _check_values_indices_shape_match
    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")
ValueError: Shape of passed values is (34036, 1), indices imply (34036, 25505)

2025-04-10 14:42:40,813-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 14:42:40,974-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 14:42:41,354-__main__-INFO-Preprocessing features
2025-04-10 14:42:54,303-__main__-INFO-Applying SMOTE for class balancing
2025-04-10 15:24:02,034-__main__-INFO-Balanced dataset saved to: artifacts/feature_eng/processed_data.csv
2025-04-10 15:24:02,655-__main__-INFO-Unique Values in Case Status: 
case_status
1    17018
0    17018
Name: count, dtype: int64
2025-04-10 17:07:02,417-__main__-INFO-Train dataset saved to artifacts/feature_eng/train_data.csv
2025-04-10 17:07:02,502-__main__-INFO-Test dataset saved to artifacts/feature_eng/test_path
2025-04-10 17:07:03,249-__main__-INFO-Feature Engineering Process Completed...
2025-04-10 17:28:29,278-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 17:28:29,440-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 17:28:30,050-__main__-INFO-Preprocessing features
2025-04-10 17:28:46,078-__main__-INFO-Applying SMOTE for class balancing
2025-04-10 18:05:53,453-__main__-INFO-Balanced dataset saved to: artifacts/feature_eng/processed_data.csv
2025-04-10 18:05:53,940-__main__-INFO-Unique Values in Case Status: 
case_status
1    17018
0    17018
Name: count, dtype: int64
2025-04-10 18:50:43,605-__main__-INFO-Train dataset saved to artifacts/feature_eng/train_data.csv
2025-04-10 18:50:43,711-__main__-INFO-Test dataset saved to artifacts/feature_eng/test_path.csv
2025-04-10 18:50:44,343-__main__-INFO-Feature Engineering Process Completed...
2025-04-10 19:43:13,896-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 19:43:14,615-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 19:43:14,957-__main__-INFO-Preprocessing features
2025-04-10 19:43:28,050-__main__-INFO-Applying SMOTE for class balancing
2025-04-10 20:19:25,372-__main__-INFO-Balanced dataset saved to: artifacts/feature_eng/processed_data.csv
2025-04-10 20:19:25,488-__main__-INFO-Unique Values in Case Status: 
case_status
Denied       17018
Certified    17018
Name: count, dtype: int64
2025-04-10 20:51:01,442-__main__-INFO-Train dataset saved to artifacts/feature_eng/train_data.csv
2025-04-10 20:51:01,456-__main__-INFO-Test dataset saved to artifacts/feature_eng/test_data.csv
2025-04-10 20:51:01,859-__main__-INFO-Feature Engineering Process Completed...
2025-04-10 21:29:45,987-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 21:29:46,188-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 21:29:46,480-__main__-INFO-Preprocessing features
2025-04-10 21:29:46,499-src.exception-ERROR-Error Message: LabelEncoder.fit_transform() takes 2 positional arguments but 3 were given
2025-04-10 21:29:46,738-src.exception-ERROR-Error Details: (<class 'TypeError'>, TypeError('LabelEncoder.fit_transform() takes 2 positional arguments but 3 were given'), <traceback object at 0x121f22ec0>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 93, in initiate_feature_engineering
    X_preprocessed = preprocessor.fit_transform(X)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py", line 727, in fit_transform
    result = self._fit_transform(X, y, _fit_transform_one)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py", line 658, in _fit_transform
    return Parallel(n_jobs=self.n_jobs)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/parallel.py", line 63, in __call__
    return super().__call__(iterable_with_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/parallel.py", line 1088, in __call__
    while self.dispatch_one_batch(iterator):
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/_parallel_backends.py", line 597, in __init__
    self.results = batch()
                   ^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/parallel.py", line 123, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/pipeline.py", line 893, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/pipeline.py", line 445, in fit_transform
    return last_step.fit_transform(Xt, y, **fit_params_last_step)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LabelEncoder.fit_transform() takes 2 positional arguments but 3 were given

2025-04-10 22:01:05,557-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 22:01:05,709-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 22:01:06,242-__main__-INFO-Preprocessing features
2025-04-10 22:01:06,277-src.exception-ERROR-Error Message: could not convert string to float: 'EZYV01'
2025-04-10 22:01:06,804-src.exception-ERROR-Error Details: (<class 'ValueError'>, ValueError("could not convert string to float: 'EZYV01'"), <traceback object at 0x12f522d40>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 96, in initiate_feature_engineering
    X_preprocessed = preprocessor.fit_transform(X)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py", line 727, in fit_transform
    result = self._fit_transform(X, y, _fit_transform_one)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py", line 658, in _fit_transform
    return Parallel(n_jobs=self.n_jobs)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/parallel.py", line 63, in __call__
    return super().__call__(iterable_with_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/_parallel_backends.py", line 597, in __init__
    self.results = batch()
                   ^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/parallel.py", line 123, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/pipeline.py", line 893, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/pipeline.py", line 445, in fit_transform
    return last_step.fit_transform(Xt, y, **fit_params_last_step)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 878, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_data.py", line 427, in fit
    return self.partial_fit(X, y)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_data.py", line 466, in partial_fit
    X = self._validate_data(
        ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 565, in _validate_data
    X = check_array(X, input_name="X", **check_params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py", line 879, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/_array_api.py", line 185, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/generic.py", line 2084, in __array__
    arr = np.asarray(values, dtype=dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'EZYV01'

2025-04-10 22:03:38,791-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 22:03:38,926-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 22:03:39,384-__main__-INFO-Preprocessing features
2025-04-10 22:03:39,433-__main__-INFO-Applying SMOTE for class balancing
2025-04-10 22:03:39,950-src.exception-ERROR-Error Message: input_features is not equal to feature_names_in_
2025-04-10 22:03:39,969-src.exception-ERROR-Error Details: (<class 'ValueError'>, ValueError('input_features is not equal to feature_names_in_'), <traceback object at 0x1089e9600>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 105, in initiate_feature_engineering
    preprocessor.named_transformers_['num'].get_feature_names_out(numerical_cols).tolist() +
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/pipeline.py", line 756, in get_feature_names_out
    feature_names_out = transform.get_feature_names_out(feature_names_out)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 911, in get_feature_names_out
    return _check_feature_names_in(self, input_features)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py", line 1954, in _check_feature_names_in
    raise ValueError("input_features is not equal to feature_names_in_")
ValueError: input_features is not equal to feature_names_in_

2025-04-10 22:11:54,110-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 22:11:54,711-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 22:11:55,327-__main__-INFO-Preprocessing features
2025-04-10 22:11:55,338-__main__-INFO-Applying SMOTE for class balancing
2025-04-10 22:11:55,502-src.exception-ERROR-Error Message: Shape of passed values is (34036, 3), indices imply (34036, 11)
2025-04-10 22:11:56,082-src.exception-ERROR-Error Details: (<class 'ValueError'>, ValueError('Shape of passed values is (34036, 3), indices imply (34036, 11)'), <traceback object at 0x129f65a00>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 103, in initiate_feature_engineering
    X_df = pd.DataFrame(X_balanced, columns=feature_names)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/frame.py", line 782, in __init__
    mgr = ndarray_to_mgr(
          ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 336, in ndarray_to_mgr
    _check_values_indices_shape_match(values, index, columns)
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 420, in _check_values_indices_shape_match
    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")
ValueError: Shape of passed values is (34036, 3), indices imply (34036, 11)

2025-04-10 22:15:44,545-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 22:15:44,927-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 22:15:45,448-__main__-INFO-Preprocessing features
2025-04-10 22:15:45,465-__main__-INFO-Applying SMOTE for class balancing
2025-04-10 22:15:45,648-src.exception-ERROR-Error Message: 'cat'
2025-04-10 22:15:45,651-src.exception-ERROR-Error Details: (<class 'KeyError'>, KeyError('cat'), <traceback object at 0x125cb76c0>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 104, in initiate_feature_engineering
    preprocessor.named_transformers_['cat'].get_feature_names_out(categorical_cols).tolist()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'cat'

2025-04-10 22:21:22,274-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 22:21:22,392-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 22:21:22,795-__main__-INFO-Preprocessing features
2025-04-10 22:21:22,813-__main__-INFO-Applying SMOTE for class balancing
2025-04-10 22:21:27,042-__main__-INFO-Balanced dataset saved to: artifacts/feature_eng/processed_data.csv
2025-04-10 22:21:27,053-__main__-INFO-Unique Values in Case Status: 
case_status
Denied       17018
Certified    17018
Name: count, dtype: int64
2025-04-10 22:21:40,485-__main__-INFO-Train dataset saved to artifacts/feature_eng/train_data.csv
2025-04-10 22:21:40,486-__main__-INFO-Test dataset saved to artifacts/feature_eng/test_data.csv
2025-04-10 22:21:40,494-__main__-INFO-Feature Engineering Process Completed...
2025-04-10 22:22:57,041-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 22:22:57,204-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 22:22:57,666-__main__-INFO-Preprocessing features
2025-04-10 22:22:57,686-__main__-INFO-Applying SMOTE for class balancing
2025-04-10 22:22:58,370-__main__-INFO-Balanced dataset saved to: artifacts/feature_eng/processed_data.csv
2025-04-10 22:22:58,381-__main__-INFO-Unique Values in Case Status: 
case_status
Denied       17018
Certified    17018
Name: count, dtype: int64
2025-04-10 22:22:58,975-__main__-INFO-Train dataset saved to artifacts/feature_eng/train_data.csv
2025-04-10 22:22:58,976-__main__-INFO-Test dataset saved to artifacts/feature_eng/test_data.csv
2025-04-10 22:22:58,984-__main__-INFO-Feature Engineering Process Completed...
2025-04-10 22:24:38,675-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 22:24:38,831-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 22:24:39,270-__main__-INFO-Preprocessing features
2025-04-10 22:24:39,292-__main__-INFO-Applying SMOTE for class balancing
2025-04-10 22:24:39,439-src.exception-ERROR-Error Message: Shape of passed values is (34036, 3), indices imply (34036, 11)
2025-04-10 22:24:39,459-src.exception-ERROR-Error Details: (<class 'ValueError'>, ValueError('Shape of passed values is (34036, 3), indices imply (34036, 11)'), <traceback object at 0x12b7155c0>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 105, in initiate_feature_engineering
    X_df = pd.DataFrame(X_balanced, columns=feature_names)  # Adjust the column slice
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/frame.py", line 782, in __init__
    mgr = ndarray_to_mgr(
          ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 336, in ndarray_to_mgr
    _check_values_indices_shape_match(values, index, columns)
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 420, in _check_values_indices_shape_match
    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")
ValueError: Shape of passed values is (34036, 3), indices imply (34036, 11)

2025-04-10 22:31:27,682-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 22:31:27,804-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 22:31:28,307-__main__-INFO-Preprocessing features
2025-04-10 22:31:28,334-__main__-INFO-Applying SMOTE for class balancing
2025-04-10 22:31:28,495-src.exception-ERROR-Error Message: Shape of passed values is (34036, 3), indices imply (34036, 11)
2025-04-10 22:31:28,520-src.exception-ERROR-Error Details: (<class 'ValueError'>, ValueError('Shape of passed values is (34036, 3), indices imply (34036, 11)'), <traceback object at 0x12d23d9c0>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 105, in initiate_feature_engineering
    X_df = pd.DataFrame(X_balanced, columns=numerical_cols)  # Adjust the column slice
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/frame.py", line 782, in __init__
    mgr = ndarray_to_mgr(
          ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 336, in ndarray_to_mgr
    _check_values_indices_shape_match(values, index, columns)
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 420, in _check_values_indices_shape_match
    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")
ValueError: Shape of passed values is (34036, 3), indices imply (34036, 11)

2025-04-10 22:47:57,396-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 22:47:57,581-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 22:47:57,950-__main__-INFO-Preprocessing features
2025-04-10 22:47:57,978-src.exception-ERROR-Error Message: 'LabelEncoder' object is not callable
2025-04-10 22:47:58,061-src.exception-ERROR-Error Details: (<class 'TypeError'>, TypeError("'LabelEncoder' object is not callable"), <traceback object at 0x1286cfa80>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 96, in initiate_feature_engineering
    X_preprocessed = preprocessor.fit_transform(X)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py", line 727, in fit_transform
    result = self._fit_transform(X, y, _fit_transform_one)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py", line 658, in _fit_transform
    return Parallel(n_jobs=self.n_jobs)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/parallel.py", line 63, in __call__
    return super().__call__(iterable_with_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/parallel.py", line 1088, in __call__
    while self.dispatch_one_batch(iterator):
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/_parallel_backends.py", line 597, in __init__
    self.results = batch()
                   ^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/parallel.py", line 123, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/pipeline.py", line 893, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 878, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_function_transformer.py", line 238, in transform
    return self._transform(X, func=self.func, kw_args=self.kw_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_function_transformer.py", line 310, in _transform
    return func(X, **(kw_args if kw_args else {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 91, in <lambda>
    ("cat", FunctionTransformer(lambda x: le(x, categorical_cols), validate=False), categorical_cols)
                                          ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'LabelEncoder' object is not callable

2025-04-10 22:54:30,124-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 22:54:30,255-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 22:54:30,734-__main__-INFO-Preprocessing features
2025-04-10 22:54:30,757-src.exception-ERROR-Error Message: 'LabelEncoder' object is not callable
2025-04-10 22:54:30,785-src.exception-ERROR-Error Details: (<class 'TypeError'>, TypeError("'LabelEncoder' object is not callable"), <traceback object at 0x12aae7b40>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 96, in initiate_feature_engineering
    X_preprocessed = preprocessor.fit_transform(X)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py", line 727, in fit_transform
    result = self._fit_transform(X, y, _fit_transform_one)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py", line 658, in _fit_transform
    return Parallel(n_jobs=self.n_jobs)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/parallel.py", line 63, in __call__
    return super().__call__(iterable_with_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/parallel.py", line 1088, in __call__
    while self.dispatch_one_batch(iterator):
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/_parallel_backends.py", line 597, in __init__
    self.results = batch()
                   ^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/parallel.py", line 123, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/pipeline.py", line 893, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 878, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_function_transformer.py", line 238, in transform
    return self._transform(X, func=self.func, kw_args=self.kw_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_function_transformer.py", line 310, in _transform
    return func(X, **(kw_args if kw_args else {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 91, in <lambda>
    ("cat", FunctionTransformer(lambda x: le(x, categorical_cols), validate=False), categorical_cols)
                                          ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'LabelEncoder' object is not callable

2025-04-10 22:56:24,143-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 22:56:24,263-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 22:56:24,699-__main__-INFO-Preprocessing features
2025-04-10 22:56:24,717-__main__-INFO-Applying SMOTE for class balancing
2025-04-10 22:56:24,861-src.exception-ERROR-Error Message: Shape of passed values is (34036, 3), indices imply (34036, 11)
2025-04-10 22:56:24,882-src.exception-ERROR-Error Details: (<class 'ValueError'>, ValueError('Shape of passed values is (34036, 3), indices imply (34036, 11)'), <traceback object at 0x12a3bd800>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 105, in initiate_feature_engineering
    X_df = pd.DataFrame(X_balanced, columns=numerical_cols)  # Adjust the column slice
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/frame.py", line 782, in __init__
    mgr = ndarray_to_mgr(
          ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 336, in ndarray_to_mgr
    _check_values_indices_shape_match(values, index, columns)
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 420, in _check_values_indices_shape_match
    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")
ValueError: Shape of passed values is (34036, 3), indices imply (34036, 11)

2025-04-10 23:03:36,903-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 23:03:37,038-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 23:03:37,433-__main__-INFO-Preprocessing features
2025-04-10 23:03:37,460-__main__-INFO-Applying SMOTE for class balancing
2025-04-10 23:03:37,599-src.exception-ERROR-Error Message: Shape of passed values is (34036, 3), indices imply (34036, 2)
2025-04-10 23:03:37,619-src.exception-ERROR-Error Details: (<class 'ValueError'>, ValueError('Shape of passed values is (34036, 3), indices imply (34036, 2)'), <traceback object at 0x12b83a5c0>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 105, in initiate_feature_engineering
    X_df = pd.DataFrame(X_balanced, columns=numerical_cols)  # Adjust the column slice
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/frame.py", line 782, in __init__
    mgr = ndarray_to_mgr(
          ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 336, in ndarray_to_mgr
    _check_values_indices_shape_match(values, index, columns)
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 420, in _check_values_indices_shape_match
    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")
ValueError: Shape of passed values is (34036, 3), indices imply (34036, 2)

2025-04-10 23:06:40,074-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 23:06:40,253-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 23:06:40,722-__main__-INFO-Preprocessing features
2025-04-10 23:06:40,735-__main__-INFO-Applying SMOTE for class balancing
2025-04-10 23:06:40,876-src.exception-ERROR-Error Message: operands could not be broadcast together with shapes (34036,3) (34036,) 
2025-04-10 23:06:41,209-src.exception-ERROR-Error Details: (<class 'ValueError'>, ValueError('operands could not be broadcast together with shapes (34036,3) (34036,) '), <traceback object at 0x127c6d980>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 102, in initiate_feature_engineering
    total_cols = X_balanced + y_balanced
                 ~~~~~~~~~~~^~~~~~~~~~~~
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/generic.py", line 2102, in __array_ufunc__
    return arraylike.array_ufunc(self, ufunc, method, *inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/arraylike.py", line 273, in array_ufunc
    result = maybe_dispatch_ufunc_to_dunder_op(self, ufunc, method, *inputs, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ops_dispatch.pyx", line 113, in pandas._libs.ops_dispatch.maybe_dispatch_ufunc_to_dunder_op
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/arraylike.py", line 190, in __radd__
    return self._arith_method(other, roperator.radd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/series.py", line 5819, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/base.py", line 1381, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 285, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)  # type: ignore[arg-type]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 220, in _na_arithmetic_op
    result = func(left, right)
             ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/computation/expressions.py", line 242, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/computation/expressions.py", line 131, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/computation/expressions.py", line 73, in _evaluate_standard
    return op(a, b)
           ^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/roperator.py", line 11, in radd
    return right + left
           ~~~~~~^~~~~~
ValueError: operands could not be broadcast together with shapes (34036,3) (34036,) 

2025-04-10 23:09:37,331-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 23:09:37,460-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 23:09:37,921-__main__-INFO-Preprocessing features
2025-04-10 23:09:37,939-__main__-INFO-Applying SMOTE for class balancing
2025-04-10 23:09:38,078-src.exception-ERROR-Error Message: Shape of passed values is (34036, 3), indices imply (34036, 11)
2025-04-10 23:09:38,102-src.exception-ERROR-Error Details: (<class 'ValueError'>, ValueError('Shape of passed values is (34036, 3), indices imply (34036, 11)'), <traceback object at 0x123db1c80>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 105, in initiate_feature_engineering
    X_df = pd.DataFrame(X_balanced, columns=numerical_cols)  # Adjust the column slice
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/frame.py", line 782, in __init__
    mgr = ndarray_to_mgr(
          ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 336, in ndarray_to_mgr
    _check_values_indices_shape_match(values, index, columns)
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 420, in _check_values_indices_shape_match
    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")
ValueError: Shape of passed values is (34036, 3), indices imply (34036, 11)

2025-04-10 23:11:58,541-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 23:11:58,683-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 23:11:59,111-__main__-INFO-Preprocessing features
2025-04-10 23:11:59,127-__main__-INFO-Applying SMOTE for class balancing
2025-04-10 23:11:59,271-src.exception-ERROR-Error Message: name 'y_resampled' is not defined
2025-04-10 23:11:59,275-src.exception-ERROR-Error Details: (<class 'NameError'>, NameError("name 'y_resampled' is not defined"), <traceback object at 0x12a315e00>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 103, in initiate_feature_engineering
    balanced_df = pd.concat([pd.DataFrame(X_balanced), pd.Series(y_resampled, name=target_col)], axis=1)
                                                                 ^^^^^^^^^^^
NameError: name 'y_resampled' is not defined

2025-04-10 23:12:24,598-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 23:12:24,755-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 23:12:25,183-__main__-INFO-Preprocessing features
2025-04-10 23:12:25,200-__main__-INFO-Applying SMOTE for class balancing
2025-04-10 23:12:25,804-__main__-INFO-Balanced dataset saved to: artifacts/feature_eng/processed_data.csv
2025-04-10 23:12:25,810-__main__-INFO-Unique Values in Case Status: 
case_status
Denied       17018
Certified    17018
Name: count, dtype: int64
2025-04-10 23:12:25,873-src.exception-ERROR-Error Message: too many values to unpack (expected 2)
2025-04-10 23:12:25,878-src.exception-ERROR-Error Details: (<class 'ValueError'>, ValueError('too many values to unpack (expected 2)'), <traceback object at 0x125a4f240>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 111, in initiate_feature_engineering
    train_df, test_df = train_test_split(
    ^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)

2025-04-10 23:14:35,569-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 23:14:35,712-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 23:14:36,116-__main__-INFO-Preprocessing features
2025-04-10 23:14:36,130-__main__-INFO-Applying SMOTE for class balancing
2025-04-10 23:14:36,532-__main__-INFO-Balanced dataset saved to: artifacts/feature_eng/processed_data.csv
2025-04-10 23:14:36,547-__main__-INFO-Unique Values in Case Status: 
case_status
Denied       17018
Certified    17018
Name: count, dtype: int64
2025-04-10 23:14:36,865-__main__-INFO-Train dataset saved to artifacts/feature_eng/train_data.csv
2025-04-10 23:14:36,865-__main__-INFO-Test dataset saved to artifacts/feature_eng/test_data.csv
2025-04-10 23:14:36,871-__main__-INFO-Feature Engineering Process Completed...
2025-04-10 23:19:41,192-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 23:19:41,311-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 23:19:41,779-__main__-INFO-Preprocessing features
2025-04-10 23:19:41,803-__main__-INFO-Applying SMOTE for class balancing
2025-04-10 23:19:41,961-src.exception-ERROR-Error Message: Index data must be 1-dimensional
2025-04-10 23:19:42,277-src.exception-ERROR-Error Details: (<class 'ValueError'>, ValueError('Index data must be 1-dimensional'), <traceback object at 0x130cd2100>)Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 560, in __new__
    arr = sanitize_array(data, None, dtype=dtype, copy=copy)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/construction.py", line 658, in sanitize_array
    subarr = _sanitize_ndim(subarr, data, dtype, index, allow_2d=allow_2d)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/construction.py", line 717, in _sanitize_ndim
    raise ValueError(
ValueError: Data must be 1-dimensional, got ndarray of shape (25480, 11) instead

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 103, in initiate_feature_engineering
    balanced_df = pd.concat([pd.DataFrame(X_balanced,columns=X), pd.Series(y_balanced, name=target_col)], axis=1)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/frame.py", line 782, in __init__
    mgr = ndarray_to_mgr(
          ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 332, in ndarray_to_mgr
    index, columns = _get_axes(
                     ^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 756, in _get_axes
    columns = ensure_index(columns)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 7577, in ensure_index
    return Index(index_like, copy=copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 527, in __new__
    return Index(np.asarray(data), dtype=dtype, copy=copy, name=name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 565, in __new__
    raise ValueError("Index data must be 1-dimensional") from err
ValueError: Index data must be 1-dimensional

2025-04-10 23:34:53,860-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 23:34:54,128-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 23:34:54,524-src.exception-ERROR-Error Message: could not convert string to float: 'EZYV7232'
2025-04-10 23:34:54,554-src.exception-ERROR-Error Details: (<class 'ValueError'>, ValueError("could not convert string to float: 'EZYV7232'"), <traceback object at 0x130c62440>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 82, in initiate_feature_engineering
    X_train_scaled = scaler.fit_transform(X_train)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 878, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_data.py", line 427, in fit
    return self.partial_fit(X, y)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_data.py", line 466, in partial_fit
    X = self._validate_data(
        ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 565, in _validate_data
    X = check_array(X, input_name="X", **check_params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py", line 879, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/_array_api.py", line 185, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/generic.py", line 2084, in __array__
    arr = np.asarray(values, dtype=dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'EZYV7232'

2025-04-10 23:43:59,617-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 23:43:59,724-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 23:44:00,057-src.exception-ERROR-Error Message: could not convert string to float: 'Year'
2025-04-10 23:44:00,086-src.exception-ERROR-Error Details: (<class 'ValueError'>, ValueError("could not convert string to float: 'Year'"), <traceback object at 0x1296ade80>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 85, in initiate_feature_engineering
    X[numeric_columns] = scaler.fit_transform(X[numeric_columns])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 878, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_data.py", line 427, in fit
    return self.partial_fit(X, y)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_data.py", line 466, in partial_fit
    X = self._validate_data(
        ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 565, in _validate_data
    X = check_array(X, input_name="X", **check_params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py", line 879, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/_array_api.py", line 185, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/generic.py", line 2084, in __array__
    arr = np.asarray(values, dtype=dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'Year'

2025-04-10 23:51:39,483-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 23:51:39,653-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 23:51:39,915-src.exception-ERROR-Error Message: could not convert string to float: 'Hour'
2025-04-10 23:51:39,945-src.exception-ERROR-Error Details: (<class 'ValueError'>, ValueError("could not convert string to float: 'Hour'"), <traceback object at 0x12ad01dc0>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 65, in initiate_feature_engineering
    X[numeric_columns] = scaler.fit_transform(X[numeric_columns])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 878, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_data.py", line 427, in fit
    return self.partial_fit(X, y)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_data.py", line 466, in partial_fit
    X = self._validate_data(
        ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 565, in _validate_data
    X = check_array(X, input_name="X", **check_params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py", line 879, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/_array_api.py", line 185, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/generic.py", line 2084, in __array__
    arr = np.asarray(values, dtype=dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'Hour'

2025-04-10 23:52:37,753-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 23:52:37,953-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 23:52:38,106-src.exception-ERROR-Error Message: could not convert string to float: 'EZYV7232'
2025-04-10 23:52:38,255-src.exception-ERROR-Error Details: (<class 'ValueError'>, ValueError("could not convert string to float: 'EZYV7232'"), <traceback object at 0x12b764740>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 84, in initiate_feature_engineering
    X_train_res, y_train_res = smote.fit_resample(X_train, y_train)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/imblearn/base.py", line 208, in fit_resample
    return super().fit_resample(X, y)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/imblearn/base.py", line 106, in fit_resample
    X, y, binarize_y = self._check_X_y(X, y)
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/imblearn/base.py", line 161, in _check_X_y
    X, y = self._validate_data(X, y, reset=True, accept_sparse=accept_sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 584, in _validate_data
    X, y = check_X_y(X, y, **check_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py", line 1106, in check_X_y
    X = check_array(
        ^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py", line 879, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/_array_api.py", line 185, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/generic.py", line 2084, in __array__
    arr = np.asarray(values, dtype=dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'EZYV7232'

2025-04-10 23:53:20,629-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 23:53:20,752-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 23:53:21,266-__main__-INFO-Train dataset saved to artifacts/feature_eng/train_data.csv
2025-04-10 23:53:21,267-__main__-INFO-Test dataset saved to artifacts/feature_eng/test_data.csv
2025-04-10 23:53:21,270-__main__-INFO-Feature Engineering Process Completed...
2025-04-10 23:57:17,353-__main__-INFO-Starting the Feature Engineering Process....
2025-04-10 23:57:17,521-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-10 23:57:17,771-__main__-INFO-Value counts of the resampled target variable (case_status):
case_status
0    11899
1    11899
Name: count, dtype: int64
2025-04-10 23:57:17,994-__main__-INFO-Full resampled dataset saved to artifacts/feature_eng/processed_data.csv
2025-04-10 23:57:19,094-__main__-INFO-Train dataset saved to artifacts/feature_eng/train_data.csv
2025-04-10 23:57:19,098-__main__-INFO-Test dataset saved to artifacts/feature_eng/test_data.csv
2025-04-10 23:57:19,116-__main__-INFO-Feature Engineering Process Completed...
2025-04-11 00:00:58,308-__main__-INFO-Starting the Feature Engineering Process....
2025-04-11 00:00:58,429-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-11 00:00:58,820-__main__-INFO-Value counts of the resampled target variable (case_status):
case_status
1    17018
0    17018
Name: count, dtype: int64
2025-04-11 00:00:59,152-__main__-INFO-Full resampled dataset saved to artifacts/feature_eng/processed_data.csv
2025-04-11 00:00:59,785-__main__-INFO-Train dataset saved to artifacts/feature_eng/train_data.csv
2025-04-11 00:00:59,785-__main__-INFO-Test dataset saved to artifacts/feature_eng/test_data.csv
2025-04-11 00:00:59,790-__main__-INFO-Feature Engineering Process Completed...
2025-04-11 09:29:23,437-__main__-INFO-Starting the Feature Engineering Process....
2025-04-11 09:29:23,697-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-11 09:29:23,804-src.exception-ERROR-Error Message: 'region_of_emploment'
2025-04-11 09:29:23,883-src.exception-ERROR-Error Details: (<class 'KeyError'>, KeyError('region_of_emploment'), <traceback object at 0x1285fde00>)Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3791, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'region_of_emploment'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/4_feature_engineering.py", line 60, in initiate_feature_engineering
    X[column] = label_encoder.fit_transform(X[column])
                                            ~^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/frame.py", line 3893, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3798, in get_loc
    raise KeyError(key) from err
KeyError: 'region_of_emploment'

2025-04-11 09:30:20,729-__main__-INFO-Starting the Feature Engineering Process....
2025-04-11 09:30:20,929-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-11 09:30:21,570-__main__-INFO-Value counts of the resampled target variable (case_status):
case_status
1    17018
0    17018
Name: count, dtype: int64
2025-04-11 09:30:22,104-__main__-INFO-Full resampled dataset saved to artifacts/feature_eng/processed_data.csv
2025-04-11 09:30:22,551-__main__-INFO-Train dataset saved to artifacts/feature_eng/train_data.csv
2025-04-11 09:30:22,551-__main__-INFO-Test dataset saved to artifacts/feature_eng/test_data.csv
2025-04-11 09:30:22,568-__main__-INFO-Feature Engineering Process Completed...
2025-04-11 09:43:19,834-__main__-INFO-Starting the Feature Engineering Process....
2025-04-11 09:43:19,961-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-11 09:43:20,195-__main__-INFO-Value counts of the resampled target variable (case_status):
case_status
1    17018
0    17018
Name: count, dtype: int64
2025-04-11 09:43:20,485-__main__-INFO-Full resampled dataset saved to artifacts/feature_eng/processed_data.csv
2025-04-11 09:43:20,801-__main__-INFO-Train dataset saved to artifacts/feature_eng/train_data.csv
2025-04-11 09:43:20,801-__main__-INFO-Test dataset saved to artifacts/feature_eng/test_data.csv
2025-04-11 09:43:20,805-__main__-INFO-Feature Engineering Process Completed...
2025-04-11 10:32:26,294-__main__-INFO-EDA processing initialising......
2025-04-11 10:32:26,294-__main__-INFO-Loading data from: artifacts/dataset/olfc_data.csv
2025-04-11 10:32:26,296-src.exception-ERROR-Error Message: [Errno 2] No such file or directory: 'artifacts/dataset/olfc_data.csv'
2025-04-11 10:32:26,401-src.exception-ERROR-Error Details: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x11e215a80>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/2_EDA.py", line 30, in initialising_eda
    df = pd.read_csv(self.EDA_config.data_path)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/dataset/olfc_data.csv'

2025-04-11 10:32:59,574-__main__-INFO-Starting data ingestion process....
2025-04-11 10:35:59,667-__main__-INFO-Data saved to CSV at: artifacts/dataset/olfc_data.csv
2025-04-11 10:35:59,680-__main__-INFO-Data Ingestion Completed
2025-04-11 17:43:01,989-__main__-INFO-Training and Test Data Loaded Successfully
2025-04-11 17:43:01,991-src.exception-ERROR-Error Message: local variable 'X_train' referenced before assignment
2025-04-11 17:43:01,993-src.exception-ERROR-Error Details: (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'X_train' referenced before assignment"), <traceback object at 0x16e2f97c0>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/5_model_training.py", line 57, in initiate_model_training
    "LSTM":self.build_lstm_model(X_train.shape[1])
UnboundLocalError: local variable 'X_train' referenced before assignment

2025-04-11 17:46:01,125-__main__-INFO-Training and Test Data Loaded Successfully
2025-04-11 17:46:01,826-src.exception-ERROR-Error Message: 'ModelTraining' object has no attribute 'model_training_configuration'
2025-04-11 17:46:01,831-src.exception-ERROR-Error Details: (<class 'AttributeError'>, AttributeError("'ModelTraining' object has no attribute 'model_training_configuration'"), <traceback object at 0x16b07e540>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/5_model_training.py", line 77, in initiate_model_training
    mlflow_tracking_uri = self.model_training_configuration.MLFLOW_TRACKING_URI
AttributeError: 'ModelTraining' object has no attribute 'model_training_configuration'

2025-04-11 17:49:15,295-__main__-INFO-Training and Test Data Loaded Successfully
2025-04-11 17:49:17,904-__main__-INFO-
======= Training Model: Logistic Regression ======
2025-04-11 17:49:22,479-__main__-INFO-Model: Logistic Regression | Accuracy: 0.6933 | Precision: 0.6943Recall: 0.6853F1: 0.6897 | ROC-AUC: 0.747766167854514
2025-04-11 17:49:22,480-__main__-INFO-Confusion Matrix:
[[2399 1022]
 [1066 2321]]
2025-04-11 17:49:22,480-__main__-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.70      0.70      3421
           1       0.69      0.69      0.69      3387

    accuracy                           0.69      6808
   macro avg       0.69      0.69      0.69      6808
weighted avg       0.69      0.69      0.69      6808

2025-04-11 17:49:55,790-src.exception-ERROR-Error Message: '>' not supported between instances of 'float' and 'NoneType'
2025-04-11 17:49:55,802-src.exception-ERROR-Error Details: (<class 'TypeError'>, TypeError("'>' not supported between instances of 'float' and 'NoneType'"), <traceback object at 0x170cec200>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/5_model_training.py", line 131, in initiate_model_training
    if current_roc > best_roc_auc:
TypeError: '>' not supported between instances of 'float' and 'NoneType'

2025-04-11 17:52:22,099-__main__-INFO-Training and Test Data Loaded Successfully
2025-04-11 17:52:23,343-__main__-INFO-
======= Training Model: Logistic Regression ======
2025-04-11 17:52:26,234-__main__-INFO-Model: Logistic Regression | Accuracy: 0.6933 | Precision: 0.6943Recall: 0.6853F1: 0.6897 | ROC-AUC: 0.747766167854514
2025-04-11 17:52:26,235-__main__-INFO-Confusion Matrix:
[[2399 1022]
 [1066 2321]]
2025-04-11 17:52:26,235-__main__-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.70      0.70      3421
           1       0.69      0.69      0.69      3387

    accuracy                           0.69      6808
   macro avg       0.69      0.69      0.69      6808
weighted avg       0.69      0.69      0.69      6808

2025-04-11 17:52:50,661-__main__-INFO-
======= Training Model: Decision Tree Classifier ======
2025-04-11 17:52:53,954-__main__-INFO-Model: Decision Tree Classifier | Accuracy: 0.7306 | Precision: 0.7253Recall: 0.7381F1: 0.7316 | ROC-AUC: 0.7306483418770138
2025-04-11 17:52:53,956-__main__-INFO-Confusion Matrix:
[[2474  947]
 [ 887 2500]]
2025-04-11 17:52:53,956-__main__-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.72      0.73      3421
           1       0.73      0.74      0.73      3387

    accuracy                           0.73      6808
   macro avg       0.73      0.73      0.73      6808
weighted avg       0.73      0.73      0.73      6808

2025-04-11 17:53:16,974-__main__-INFO-
======= Training Model: Xgboost ======
2025-04-11 17:53:20,346-__main__-INFO-Model: Xgboost | Accuracy: 0.7923 | Precision: 0.8119Recall: 0.7582F1: 0.7841 | ROC-AUC: 0.8752267965440708
2025-04-11 17:53:20,352-__main__-INFO-Confusion Matrix:
[[2826  595]
 [ 819 2568]]
2025-04-11 17:53:20,352-__main__-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.83      0.80      3421
           1       0.81      0.76      0.78      3387

    accuracy                           0.79      6808
   macro avg       0.79      0.79      0.79      6808
weighted avg       0.79      0.79      0.79      6808

2025-04-11 17:53:50,068-__main__-INFO-
======= Training Model: LSTM ======
2025-04-11 17:54:13,880-src.exception-ERROR-Error Message: Classification metrics can't handle a mix of binary and continuous targets
2025-04-11 17:54:14,062-src.exception-ERROR-Error Details: (<class 'ValueError'>, ValueError("Classification metrics can't handle a mix of binary and continuous targets"), <traceback object at 0x165152140>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/5_model_training.py", line 90, in initiate_model_training
    acc = accuracy_score(y_test, y_pred)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/sklearn/metrics/_classification.py", line 227, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/sklearn/metrics/_classification.py", line 107, in _check_targets
    raise ValueError(
ValueError: Classification metrics can't handle a mix of binary and continuous targets

2025-04-11 17:56:56,038-__main__-INFO-Training and Test Data Loaded Successfully
2025-04-11 17:56:57,341-__main__-INFO-
======= Training Model: Logistic Regression ======
2025-04-11 17:57:00,378-__main__-INFO-Model: Logistic Regression | Accuracy: 0.6933 | Precision: 0.6943Recall: 0.6853F1: 0.6897 | ROC-AUC: 0.747766167854514
2025-04-11 17:57:00,379-__main__-INFO-Confusion Matrix:
[[2399 1022]
 [1066 2321]]
2025-04-11 17:57:00,379-__main__-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.70      0.70      3421
           1       0.69      0.69      0.69      3387

    accuracy                           0.69      6808
   macro avg       0.69      0.69      0.69      6808
weighted avg       0.69      0.69      0.69      6808

2025-04-11 17:57:23,937-__main__-INFO-
======= Training Model: Decision Tree Classifier ======
2025-04-11 17:57:27,033-__main__-INFO-Model: Decision Tree Classifier | Accuracy: 0.7306 | Precision: 0.7253Recall: 0.7381F1: 0.7316 | ROC-AUC: 0.7306483418770138
2025-04-11 17:57:27,035-__main__-INFO-Confusion Matrix:
[[2474  947]
 [ 887 2500]]
2025-04-11 17:57:27,036-__main__-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.72      0.73      3421
           1       0.73      0.74      0.73      3387

    accuracy                           0.73      6808
   macro avg       0.73      0.73      0.73      6808
weighted avg       0.73      0.73      0.73      6808

2025-04-11 17:57:48,884-__main__-INFO-
======= Training Model: Xgboost ======
2025-04-11 17:57:52,120-__main__-INFO-Model: Xgboost | Accuracy: 0.7923 | Precision: 0.8119Recall: 0.7582F1: 0.7841 | ROC-AUC: 0.8752267965440708
2025-04-11 17:57:52,121-__main__-INFO-Confusion Matrix:
[[2826  595]
 [ 819 2568]]
2025-04-11 17:57:52,121-__main__-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.83      0.80      3421
           1       0.81      0.76      0.78      3387

    accuracy                           0.79      6808
   macro avg       0.79      0.79      0.79      6808
weighted avg       0.79      0.79      0.79      6808

2025-04-11 17:58:14,299-__main__-INFO-
======= Training Model: LSTM ======
2025-04-11 17:58:36,520-src.exception-ERROR-Error Message: Classification metrics can't handle a mix of binary and continuous targets
2025-04-11 17:58:36,530-src.exception-ERROR-Error Details: (<class 'ValueError'>, ValueError("Classification metrics can't handle a mix of binary and continuous targets"), <traceback object at 0x167d2bf80>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/5_model_training.py", line 92, in initiate_model_training
    precision =precision_score(y_test,y_pred)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/sklearn/metrics/_classification.py", line 2247, in precision_score
    p, _, _, _ = precision_recall_fscore_support(
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 189, in wrapper
    return func(*args, **kwargs)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/sklearn/metrics/_classification.py", line 1830, in precision_recall_fscore_support
    labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/sklearn/metrics/_classification.py", line 1596, in _check_set_wise_labels
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/sklearn/metrics/_classification.py", line 107, in _check_targets
    raise ValueError(
ValueError: Classification metrics can't handle a mix of binary and continuous targets

2025-04-11 18:11:13,183-__main__-INFO-Training and Test Data Loaded Successfully
2025-04-11 18:11:14,164-__main__-INFO-
======= Training Model: Logistic Regression ======
2025-04-11 18:11:16,931-__main__-INFO-Model: Logistic Regression | Accuracy: 0.6933 | Precision: 0.6943Recall: 0.6853F1: 0.6897 | ROC-AUC: 0.747766167854514
2025-04-11 18:11:16,933-__main__-INFO-Confusion Matrix:
[[2399 1022]
 [1066 2321]]
2025-04-11 18:11:16,933-__main__-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.70      0.70      3421
           1       0.69      0.69      0.69      3387

    accuracy                           0.69      6808
   macro avg       0.69      0.69      0.69      6808
weighted avg       0.69      0.69      0.69      6808

2025-04-11 18:11:41,109-__main__-INFO-
======= Training Model: Decision Tree Classifier ======
2025-04-11 18:11:44,469-__main__-INFO-Model: Decision Tree Classifier | Accuracy: 0.7306 | Precision: 0.7253Recall: 0.7381F1: 0.7316 | ROC-AUC: 0.7306483418770138
2025-04-11 18:11:44,470-__main__-INFO-Confusion Matrix:
[[2474  947]
 [ 887 2500]]
2025-04-11 18:11:44,470-__main__-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.72      0.73      3421
           1       0.73      0.74      0.73      3387

    accuracy                           0.73      6808
   macro avg       0.73      0.73      0.73      6808
weighted avg       0.73      0.73      0.73      6808

2025-04-11 18:12:06,845-__main__-INFO-
======= Training Model: Xgboost ======
2025-04-11 18:12:10,075-__main__-INFO-Model: Xgboost | Accuracy: 0.7923 | Precision: 0.8119Recall: 0.7582F1: 0.7841 | ROC-AUC: 0.8752267965440708
2025-04-11 18:12:10,076-__main__-INFO-Confusion Matrix:
[[2826  595]
 [ 819 2568]]
2025-04-11 18:12:10,076-__main__-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.83      0.80      3421
           1       0.81      0.76      0.78      3387

    accuracy                           0.79      6808
   macro avg       0.79      0.79      0.79      6808
weighted avg       0.79      0.79      0.79      6808

2025-04-11 18:12:32,683-__main__-INFO-
======= Training Model: LSTM ======
2025-04-11 18:14:35,424-__main__-INFO-Model: LSTM | Accuracy: 0.7410 | Precision: 0.7482Recall: 0.7228F1: 0.7352 | ROC-AUC: 0.8115024371863222
2025-04-11 18:14:35,436-__main__-INFO-Confusion Matrix:
[[2597  824]
 [ 939 2448]]
2025-04-11 18:14:35,436-__main__-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.73      0.76      0.75      3421
           1       0.75      0.72      0.74      3387

    accuracy                           0.74      6808
   macro avg       0.74      0.74      0.74      6808
weighted avg       0.74      0.74      0.74      6808

2025-04-11 18:14:35,945-src.exception-ERROR-Error Message: Exception encountered when calling Sequential.call().

[1mCannot take the length of shape with unknown rank.[0m

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)
  • training=False
  • mask=None
2025-04-11 18:14:36,059-src.exception-ERROR-Error Details: (<class 'ValueError'>, ValueError('Exception encountered when calling Sequential.call().\n\n\x1b[1mCannot take the length of shape with unknown rank.\x1b[0m\n\nArguments received by Sequential.call():\n  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n  • training=False\n  • mask=None'), <traceback object at 0x16969c1c0>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/5_model_training.py", line 134, in initiate_model_training
    signature = infer_signature(X_train, model.predict(X_train))
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
ValueError: Exception encountered when calling Sequential.call().

[1mCannot take the length of shape with unknown rank.[0m

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)
  • training=False
  • mask=None

2025-04-11 18:17:53,776-__main__-INFO-Starting the Feature Engineering Process....
2025-04-11 18:17:53,945-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-11 18:17:54,310-__main__-INFO-Value counts of the resampled target variable (case_status):
case_status
1    17018
0    17018
Name: count, dtype: int64
2025-04-11 18:17:54,807-__main__-INFO-Full resampled dataset saved to artifacts/feature_eng/processed_data.csv
2025-04-11 18:17:55,262-__main__-INFO-Train dataset saved to artifacts/feature_eng/train_data.csv
2025-04-11 18:17:55,262-__main__-INFO-Test dataset saved to artifacts/feature_eng/test_data.csv
2025-04-11 18:17:55,265-__main__-INFO-Feature Engineering Process Completed...
2025-04-11 18:20:20,249-__main__-INFO-Training and Test Data Loaded Successfully
2025-04-11 18:20:20,265-src.exception-ERROR-Error Message: "['case_status'] not found in axis"
2025-04-11 18:20:20,446-src.exception-ERROR-Error Details: (<class 'KeyError'>, KeyError("['case_status'] not found in axis"), <traceback object at 0x16b9e5180>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/5_model_training.py", line 55, in initiate_model_training
    X_train=train_data.drop(columns=target_column)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/core/frame.py", line 5581, in drop
    return super().drop(
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/core/generic.py", line 4788, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/core/generic.py", line 4830, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 7070, in drop
    raise KeyError(f"{labels[mask].tolist()} not found in axis")
KeyError: "['case_status'] not found in axis"

2025-04-11 18:26:44,678-__main__-INFO-Starting the Feature Engineering Process....
2025-04-11 18:26:44,816-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-11 18:26:45,765-__main__-INFO-Value counts of the resampled target variable (case_status):
case_status
1    17018
0    17018
Name: count, dtype: int64
2025-04-11 18:26:46,316-__main__-INFO-Full resampled dataset saved to artifacts/feature_eng/processed_data.csv
2025-04-11 18:26:46,800-__main__-INFO-Train dataset saved to artifacts/feature_eng/train_data.csv
2025-04-11 18:26:46,801-__main__-INFO-Test dataset saved to artifacts/feature_eng/test_data.csv
2025-04-11 18:26:46,804-__main__-INFO-Feature Engineering Process Completed...
2025-04-11 18:27:44,788-__main__-INFO-Training and Test Data Loaded Successfully
2025-04-11 18:27:45,737-__main__-INFO-
======= Training Model: Logistic Regression ======
2025-04-11 18:27:50,808-__main__-INFO-Model: Logistic Regression | Accuracy: 0.6933 | Precision: 0.6943Recall: 0.6853F1: 0.6897 | ROC-AUC: 0.747766167854514
2025-04-11 18:27:50,809-__main__-INFO-Confusion Matrix:
[[2399 1022]
 [1066 2321]]
2025-04-11 18:27:50,809-__main__-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.70      0.70      3421
           1       0.69      0.69      0.69      3387

    accuracy                           0.69      6808
   macro avg       0.69      0.69      0.69      6808
weighted avg       0.69      0.69      0.69      6808

2025-04-11 18:28:18,430-__main__-INFO-
======= Training Model: Decision Tree Classifier ======
2025-04-11 18:28:21,670-__main__-INFO-Model: Decision Tree Classifier | Accuracy: 0.7306 | Precision: 0.7253Recall: 0.7381F1: 0.7316 | ROC-AUC: 0.7306483418770138
2025-04-11 18:28:21,671-__main__-INFO-Confusion Matrix:
[[2474  947]
 [ 887 2500]]
2025-04-11 18:28:21,671-__main__-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.72      0.73      3421
           1       0.73      0.74      0.73      3387

    accuracy                           0.73      6808
   macro avg       0.73      0.73      0.73      6808
weighted avg       0.73      0.73      0.73      6808

2025-04-11 18:28:44,005-__main__-INFO-
======= Training Model: Xgboost ======
2025-04-11 18:28:47,269-__main__-INFO-Model: Xgboost | Accuracy: 0.7923 | Precision: 0.8119Recall: 0.7582F1: 0.7841 | ROC-AUC: 0.8752267965440708
2025-04-11 18:28:47,270-__main__-INFO-Confusion Matrix:
[[2826  595]
 [ 819 2568]]
2025-04-11 18:28:47,270-__main__-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.83      0.80      3421
           1       0.81      0.76      0.78      3387

    accuracy                           0.79      6808
   macro avg       0.79      0.79      0.79      6808
weighted avg       0.79      0.79      0.79      6808

2025-04-11 18:29:11,250-__main__-INFO-
======= Training Model: LSTM ======
2025-04-11 18:31:17,095-__main__-INFO-Model: LSTM | Accuracy: 0.7428 | Precision: 0.8014Recall: 0.6422F1: 0.7130 | ROC-AUC: 0.8154868413342036
2025-04-11 18:31:17,106-__main__-INFO-Confusion Matrix:
[[2882  539]
 [1212 2175]]
2025-04-11 18:31:17,107-__main__-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.70      0.84      0.77      3421
           1       0.80      0.64      0.71      3387

    accuracy                           0.74      6808
   macro avg       0.75      0.74      0.74      6808
weighted avg       0.75      0.74      0.74      6808

2025-04-11 18:32:21,372-__main__-INFO-
Best Model: Xgboost with ROC-AUC: 0.8752
2025-04-11 18:32:21,408-__main__-INFO-Best model saved to: artifacts/model.pkl
2025-04-11 18:32:21,413-__main__-INFO-Model Training Process Completed...
2025-04-11 18:33:34,158-__main__-INFO-Training and Test Data Loaded Successfully
2025-04-11 18:33:35,411-__main__-INFO-
======= Training Model: Logistic Regression ======
2025-04-11 18:33:38,388-__main__-INFO-Model: Logistic Regression | Accuracy: 0.6933 | Precision: 0.6943Recall: 0.6853F1: 0.6897 | ROC-AUC: 0.747766167854514
2025-04-11 18:33:38,391-__main__-INFO-Confusion Matrix:
[[2399 1022]
 [1066 2321]]
2025-04-11 18:33:38,392-__main__-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.70      0.70      3421
           1       0.69      0.69      0.69      3387

    accuracy                           0.69      6808
   macro avg       0.69      0.69      0.69      6808
weighted avg       0.69      0.69      0.69      6808

2025-04-11 18:34:13,062-__main__-INFO-
======= Training Model: Decision Tree Classifier ======
2025-04-11 18:34:16,083-__main__-INFO-Model: Decision Tree Classifier | Accuracy: 0.7306 | Precision: 0.7253Recall: 0.7381F1: 0.7316 | ROC-AUC: 0.7306483418770138
2025-04-11 18:34:16,084-__main__-INFO-Confusion Matrix:
[[2474  947]
 [ 887 2500]]
2025-04-11 18:34:16,085-__main__-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.72      0.73      3421
           1       0.73      0.74      0.73      3387

    accuracy                           0.73      6808
   macro avg       0.73      0.73      0.73      6808
weighted avg       0.73      0.73      0.73      6808

2025-04-11 18:34:48,663-__main__-INFO-
======= Training Model: Xgboost ======
2025-04-11 18:34:51,772-__main__-INFO-Model: Xgboost | Accuracy: 0.7923 | Precision: 0.8119Recall: 0.7582F1: 0.7841 | ROC-AUC: 0.8752267965440708
2025-04-11 18:34:51,774-__main__-INFO-Confusion Matrix:
[[2826  595]
 [ 819 2568]]
2025-04-11 18:34:51,776-__main__-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.83      0.80      3421
           1       0.81      0.76      0.78      3387

    accuracy                           0.79      6808
   macro avg       0.79      0.79      0.79      6808
weighted avg       0.79      0.79      0.79      6808

2025-04-11 18:35:25,509-__main__-INFO-
======= Training Model: LSTM ======
2025-04-11 18:37:57,815-__main__-INFO-Model: LSTM | Accuracy: 0.7457 | Precision: 0.7688Recall: 0.6991F1: 0.7323 | ROC-AUC: 0.813613997913338
2025-04-11 18:37:57,828-__main__-INFO-Confusion Matrix:
[[2709  712]
 [1019 2368]]
2025-04-11 18:37:57,828-__main__-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.73      0.79      0.76      3421
           1       0.77      0.70      0.73      3387

    accuracy                           0.75      6808
   macro avg       0.75      0.75      0.75      6808
weighted avg       0.75      0.75      0.75      6808

2025-04-11 18:39:20,935-__main__-INFO-
Best Model: Xgboost with ROC-AUC: 0.8752
2025-04-11 18:39:21,150-__main__-INFO-Best model saved to: artifacts/model.pkl
2025-04-11 18:39:21,155-__main__-INFO-Model Training Process Completed...
2025-04-13 20:53:58,552-__main__-INFO-Training and Test Data Loaded for Hyperparameter Tuning
2025-04-13 20:53:58,577-__main__-INFO-Starting hyperparameter tuning...
2025-04-13 20:55:49,458-__main__-INFO-Training and Test Data Loaded for Hyperparameter Tuning
2025-04-13 20:55:49,472-__main__-INFO-Starting hyperparameter tuning...
2025-04-13 21:00:25,843-src.exception-ERROR-Error Message: API request to https://dagshub.com/OluomaOji/easy_labor_prediction_project_with_ml.mlflow/api/2.0/mlflow/experiments/get failed with exception HTTPSConnectionPool(host='dagshub.com', port=443): Max retries exceeded with url: /OluomaOji/easy_labor_prediction_project_with_ml.mlflow/api/2.0/mlflow/experiments/get?experiment_id=None (Caused by ResponseError('too many 500 error responses'))
2025-04-13 21:00:25,897-src.exception-ERROR-Error Details: (<class 'mlflow.exceptions.MlflowException'>, MlflowException("API request to https://dagshub.com/OluomaOji/easy_labor_prediction_project_with_ml.mlflow/api/2.0/mlflow/experiments/get failed with exception HTTPSConnectionPool(host='dagshub.com', port=443): Max retries exceeded with url: /OluomaOji/easy_labor_prediction_project_with_ml.mlflow/api/2.0/mlflow/experiments/get?experiment_id=None (Caused by ResponseError('too many 500 error responses'))"), <traceback object at 0x12784f680>)urllib3.exceptions.ResponseError: too many 500 error responses

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/urllib3/connectionpool.py", line 942, in urlopen
    return self.urlopen(
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/urllib3/connectionpool.py", line 942, in urlopen
    return self.urlopen(
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/urllib3/connectionpool.py", line 942, in urlopen
    return self.urlopen(
  [Previous line repeated 4 more times]
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/urllib3/connectionpool.py", line 932, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dagshub.com', port=443): Max retries exceeded with url: /OluomaOji/easy_labor_prediction_project_with_ml.mlflow/api/2.0/mlflow/experiments/get?experiment_id=None (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 181, in http_request
    return _get_http_response_with_retries(
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/mlflow/utils/request_utils.py", line 237, in _get_http_response_with_retries
    return session.request(method, url, allow_redirects=allow_redirects, **kwargs)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/requests/adapters.py", line 691, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='dagshub.com', port=443): Max retries exceeded with url: /OluomaOji/easy_labor_prediction_project_with_ml.mlflow/api/2.0/mlflow/experiments/get?experiment_id=None (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/5_hyperparameter_tuning.py", line 85, in initiate_hyperparameter_tuning
    mlflow.set_experiment("XGBoost_Hyperparameter_Tuning")
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 172, in set_experiment
    experiment = client.get_experiment(experiment_id)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/mlflow/tracking/client.py", line 1664, in get_experiment
    return self._tracking_client.get_experiment(experiment_id)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 576, in get_experiment
    return self.store.get_experiment(experiment_id)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 149, in get_experiment
    response_proto = self._call_endpoint(GetExperiment, req_body)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 90, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 387, in call_endpoint
    response = http_request(**call_kwargs)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 204, in http_request
    raise MlflowException(f"API request to {url} failed with exception {e}")
mlflow.exceptions.MlflowException: API request to https://dagshub.com/OluomaOji/easy_labor_prediction_project_with_ml.mlflow/api/2.0/mlflow/experiments/get failed with exception HTTPSConnectionPool(host='dagshub.com', port=443): Max retries exceeded with url: /OluomaOji/easy_labor_prediction_project_with_ml.mlflow/api/2.0/mlflow/experiments/get?experiment_id=None (Caused by ResponseError('too many 500 error responses'))

2025-04-13 21:04:55,995-__main__-INFO-Training and Test Data Loaded for Hyperparameter Tuning
2025-04-13 21:04:56,005-__main__-INFO-Starting hyperparameter tuning...
2025-04-13 21:05:29,992-src.exception-ERROR-Error Message: 'HyperparameterTuning' object has no attribute 'model_training_config'
2025-04-13 21:05:29,996-src.exception-ERROR-Error Details: (<class 'AttributeError'>, AttributeError("'HyperparameterTuning' object has no attribute 'model_training_config'"), <traceback object at 0x129609c80>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/5_hyperparameter_tuning.py", line 84, in initiate_hyperparameter_tuning
    os.environ["MLFLOW_TRACKING_URI"] = self.model_training_config.MLFLOW_TRACKING_URI
AttributeError: 'HyperparameterTuning' object has no attribute 'model_training_config'

2025-04-13 21:06:53,177-__main__-INFO-Training and Test Data Loaded for Hyperparameter Tuning
2025-04-13 21:06:53,200-__main__-INFO-Starting hyperparameter tuning...
2025-04-13 21:07:50,690-__main__-INFO-ROC-AUC on Test Data: 0.8806
2025-04-13 21:07:50,691-__main__-INFO-Best Parameters: {'subsample': 0.8, 'reg_lambda': 2, 'reg_alpha': 1, 'n_estimators': 100, 'max_depth': 7, 'learning_rate': 0.2, 'gamma': 0.2, 'colsample_bytree': 0.8}
2025-04-13 21:07:51,052-src.exception-ERROR-Error Message: 'HyperparameterTuning' object has no attribute 'config'
2025-04-13 21:07:51,055-src.exception-ERROR-Error Details: (<class 'AttributeError'>, AttributeError("'HyperparameterTuning' object has no attribute 'config'"), <traceback object at 0x12a565600>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/5_hyperparameter_tuning.py", line 112, in initiate_hyperparameter_tuning
    dump(best_model, self.config.best_model)
AttributeError: 'HyperparameterTuning' object has no attribute 'config'

2025-04-13 21:09:09,739-__main__-INFO-Training and Test Data Loaded for Hyperparameter Tuning
2025-04-13 21:09:09,762-__main__-INFO-Starting hyperparameter tuning...
2025-04-13 21:10:16,401-__main__-INFO-ROC-AUC on Test Data: 0.8806
2025-04-13 21:10:16,404-__main__-INFO-Best Parameters: {'subsample': 0.8, 'reg_lambda': 2, 'reg_alpha': 1, 'n_estimators': 100, 'max_depth': 7, 'learning_rate': 0.2, 'gamma': 0.2, 'colsample_bytree': 0.8}
2025-04-13 21:10:16,811-__main__-INFO-Best tuned XGBoost model saved to: artifacts/model.pkl
2025-04-13 21:10:16,817-__main__-INFO-XGBoost Hyperparameter Tuning Completed...
2025-04-13 21:15:30,871-__main__-INFO-Training and Test Data Loaded for Hyperparameter Tuning
2025-04-13 21:15:30,890-__main__-INFO-Starting hyperparameter tuning...
2025-04-13 21:18:11,082-__main__-INFO-ROC-AUC on Test Data: 0.8841
2025-04-13 21:18:11,084-__main__-INFO-Best Parameters: {'subsample': 1.0, 'reg_lambda': 1, 'reg_alpha': 0, 'n_estimators': 1500, 'max_depth': 7, 'learning_rate': 0.01, 'gamma': 0.2, 'colsample_bytree': 0.8}
2025-04-13 21:18:11,574-__main__-INFO-Best tuned XGBoost model saved to: artifacts/model.pkl
2025-04-13 21:18:11,598-__main__-INFO-XGBoost Hyperparameter Tuning Completed...
2025-04-15 20:31:55,878-__main__-INFO-Training and Test Data Loaded for Hyperparameter Tuning
2025-04-15 20:31:55,900-__main__-INFO-Starting hyperparameter tuning...
2025-04-15 20:34:37,085-__main__-INFO-ROC-AUC on Test Data: 0.8841
2025-04-15 20:34:37,088-__main__-INFO-Best Parameters: {'subsample': 1.0, 'reg_lambda': 1, 'reg_alpha': 0, 'n_estimators': 1500, 'max_depth': 7, 'learning_rate': 0.01, 'gamma': 0.2, 'colsample_bytree': 0.8}
2025-04-15 20:34:37,944-__main__-INFO-Best tuned XGBoost model saved to: artifacts/model.pkl
2025-04-15 20:34:37,961-__main__-INFO-XGBoost Hyperparameter Tuning Completed...
2025-04-15 20:40:46,077-__main__-INFO-Training and Test Data Loaded for Hyperparameter Tuning
2025-04-15 20:40:46,144-__main__-INFO-Starting hyperparameter tuning...
2025-04-15 20:42:23,762-src.exception-ERROR-Error Message: 'HyperparameterTuning' object has no attribute 'model_training_config'
2025-04-15 20:42:23,767-src.exception-ERROR-Error Details: (<class 'AttributeError'>, AttributeError("'HyperparameterTuning' object has no attribute 'model_training_config'"), <traceback object at 0x12a9530c0>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/5_hyperparameter_tuning.py", line 89, in initiate_hyperparameter_tuning
    mlflow_tracking_uri = self.model_training_config.MLFLOW_TRACKING_URI
AttributeError: 'HyperparameterTuning' object has no attribute 'model_training_config'

2025-04-15 20:43:51,183-__main__-INFO-Training and Test Data Loaded for Hyperparameter Tuning
2025-04-15 20:43:51,204-__main__-INFO-Starting hyperparameter tuning...
2025-04-15 20:45:40,907-src.exception-ERROR-Error Message: 'RandomizedSearchCV' object has no attribute 'items'
2025-04-15 20:45:40,914-src.exception-ERROR-Error Details: (<class 'AttributeError'>, AttributeError("'RandomizedSearchCV' object has no attribute 'items'"), <traceback object at 0x12c3e78c0>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/5_hyperparameter_tuning.py", line 94, in initiate_hyperparameter_tuning
    for model_name, model in model.items():
AttributeError: 'RandomizedSearchCV' object has no attribute 'items'

2025-04-15 20:49:53,083-__main__-INFO-Training and Test Data Loaded for Hyperparameter Tuning
2025-04-15 20:49:53,105-__main__-INFO-Starting hyperparameter tuning...
2025-04-15 20:52:10,930-__main__-INFO-ROC-AUC on Test Data: 0.8841
2025-04-15 20:52:10,932-__main__-INFO-Best Parameters: {'subsample': 1.0, 'reg_lambda': 1, 'reg_alpha': 0, 'n_estimators': 1500, 'max_depth': 7, 'learning_rate': 0.01, 'gamma': 0.2, 'colsample_bytree': 0.8}
2025-04-15 20:52:11,416-__main__-INFO-Best tuned XGBoost model saved to: artifacts/model.pkl
2025-04-15 20:52:11,434-__main__-INFO-XGBoost Hyperparameter Tuning Completed...
2025-04-19 19:07:52,262-__main__-INFO-Training and Test Data Loaded Successfully
2025-04-19 19:07:53,369-__main__-INFO-
======= Training Model: Logistic Regression ======
2025-04-19 19:07:56,603-__main__-INFO-Model: Logistic Regression | Accuracy: 0.6933 | Precision: 0.6943Recall: 0.6853F1: 0.6897 | ROC-AUC: 0.747766167854514
2025-04-19 19:07:56,605-__main__-INFO-Confusion Matrix:
[[2399 1022]
 [1066 2321]]
2025-04-19 19:07:56,605-__main__-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.70      0.70      3421
           1       0.69      0.69      0.69      3387

    accuracy                           0.69      6808
   macro avg       0.69      0.69      0.69      6808
weighted avg       0.69      0.69      0.69      6808

2025-04-19 19:08:31,641-__main__-INFO-
======= Training Model: Decision Tree Classifier ======
2025-04-19 19:08:34,853-__main__-INFO-Model: Decision Tree Classifier | Accuracy: 0.7306 | Precision: 0.7253Recall: 0.7381F1: 0.7316 | ROC-AUC: 0.7306483418770138
2025-04-19 19:08:34,854-__main__-INFO-Confusion Matrix:
[[2474  947]
 [ 887 2500]]
2025-04-19 19:08:34,855-__main__-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.72      0.73      3421
           1       0.73      0.74      0.73      3387

    accuracy                           0.73      6808
   macro avg       0.73      0.73      0.73      6808
weighted avg       0.73      0.73      0.73      6808

2025-04-19 19:08:57,145-__main__-INFO-
======= Training Model: Xgboost ======
2025-04-19 19:09:00,556-__main__-INFO-Model: Xgboost | Accuracy: 0.7923 | Precision: 0.8119Recall: 0.7582F1: 0.7841 | ROC-AUC: 0.8752267965440708
2025-04-19 19:09:00,556-__main__-INFO-Confusion Matrix:
[[2826  595]
 [ 819 2568]]
2025-04-19 19:09:00,557-__main__-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.83      0.80      3421
           1       0.81      0.76      0.78      3387

    accuracy                           0.79      6808
   macro avg       0.79      0.79      0.79      6808
weighted avg       0.79      0.79      0.79      6808

2025-04-19 19:09:21,139-__main__-INFO-
======= Training Model: LSTM ======
2025-04-19 19:11:20,083-__main__-INFO-Model: LSTM | Accuracy: 0.7474 | Precision: 0.7721Recall: 0.6983F1: 0.7333 | ROC-AUC: 0.8145964844690916
2025-04-19 19:11:20,094-__main__-INFO-Confusion Matrix:
[[2723  698]
 [1022 2365]]
2025-04-19 19:11:20,094-__main__-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.73      0.80      0.76      3421
           1       0.77      0.70      0.73      3387

    accuracy                           0.75      6808
   macro avg       0.75      0.75      0.75      6808
weighted avg       0.75      0.75      0.75      6808

2025-04-19 19:12:22,561-__main__-INFO-
Best Model: Xgboost with ROC-AUC: 0.8752
2025-04-19 19:12:22,582-__main__-INFO-Best model saved to: artifacts/model.pkl
2025-04-19 19:12:22,587-__main__-INFO-Model Training Process Completed...
2025-04-19 19:14:07,054-__main__-INFO-Training and Test Data Loaded for Hyperparameter Tuning
2025-04-19 19:14:07,081-__main__-INFO-Starting hyperparameter tuning...
2025-04-19 19:16:10,928-__main__-INFO-ROC-AUC on Test Data: 0.8841
2025-04-19 19:16:10,929-__main__-INFO-Best Parameters: {'subsample': 1.0, 'reg_lambda': 1, 'reg_alpha': 0, 'n_estimators': 1500, 'max_depth': 7, 'learning_rate': 0.01, 'gamma': 0.2, 'colsample_bytree': 0.8}
2025-04-19 19:16:11,538-__main__-INFO-Best tuned XGBoost model saved to: artifacts/model.pkl
2025-04-19 19:16:11,554-__main__-INFO-XGBoost Hyperparameter Tuning Completed...
2025-04-19 19:41:57,868-__main__-INFO-Starting the Data Ingestion Process
2025-04-19 19:41:57,870-src.components.data_ingestion-INFO-Starting data ingestion process....
2025-04-19 19:44:39,107-src.components.data_ingestion-INFO-Data saved to CSV at: artifacts/dataset/olfc_data.csv
2025-04-19 19:44:39,122-__main__-INFO-Data Ingestion Completed
2025-04-19 19:44:39,122-__main__-INFO-Starting the Explorative Data Analysis
2025-04-19 19:44:39,126-src.components.EDA-INFO-EDA processing initialising......
2025-04-19 19:44:39,126-src.components.EDA-INFO-Loading data from: artifacts/dataset/olfc_data.csv
2025-04-19 19:44:40,662-src.components.EDA-INFO-Data loaded successfully loaded
2025-04-19 19:44:40,756-src.components.EDA-INFO-Generating the EDA Summary
2025-04-19 19:44:40,897-src.components.EDA-INFO-Data Head:   case_id continent  ... full_time_positio case_status
0  EZYV01      Asia  ...                 Y      Denied
1  EZYV02      Asia  ...                 Y   Certified
2  EZYV03      Asia  ...                 Y      Denied
3  EZYV04      Asia  ...                 Y      Denied
4  EZYV05    Africa  ...                 Y   Certified

[5 rows x 12 columns]
2025-04-19 19:44:40,900-src.components.EDA-INFO-Data Shape: (25480, 12)
2025-04-19 19:44:40,901-src.components.EDA-INFO-Data Info: <class 'pandas.core.frame.DataFrame'>
RangeIndex: 25480 entries, 0 to 25479
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   case_id                25480 non-null  object 
 1   continent              25480 non-null  object 
 2   education_of_e         25480 non-null  object 
 3   phlaosy_ejeob_experie  25480 non-null  object 
 4   rceequires_job_trai    25480 non-null  object 
 5   ninog_of_employee      25480 non-null  int64  
 6   yr_of_estab            25480 non-null  int64  
 7   region_of_emplo        25480 non-null  object 
 8   pmrevnat iling_wage    25480 non-null  float64
 9   unit_of_wage           25480 non-null  object 
 10  full_time_positio      25480 non-null  object 
 11  case_status            25480 non-null  object 
dtypes: float64(1), int64(2), object(9)
memory usage: 2.3+ MB

2025-04-19 19:44:40,961-src.components.EDA-INFO-Data Describe:        ninog_of_employee   yr_of_estab  pmrevnat iling_wage
count       25480.000000  25480.000000         25480.000000
mean         5667.043210   1979.409929         74455.814592
std         22877.928848     42.366929         52815.942327
min           -26.000000   1800.000000             2.136700
25%          1022.000000   1976.000000         34015.480000
50%          2109.000000   1997.000000         70308.210000
75%          3504.000000   2005.000000        107735.512500
max        602069.000000   2016.000000        319210.270000
2025-04-19 19:44:41,001-src.components.EDA-INFO-Duplicated Values: 0
2025-04-19 19:44:41,017-src.components.EDA-INFO-Missing Values: 
case_id                  0
continent                0
education_of_e           0
phlaosy_ejeob_experie    0
rceequires_job_trai      0
ninog_of_employee        0
yr_of_estab              0
region_of_emplo          0
pmrevnat iling_wage      0
unit_of_wage             0
full_time_positio        0
case_status              0
dtype: int64
2025-04-19 19:44:41,040-src.components.EDA-INFO-Unique Values: 
case_id                  25480
continent                    6
education_of_e               4
phlaosy_ejeob_experie        2
rceequires_job_trai          2
ninog_of_employee         7105
yr_of_estab                199
region_of_emplo              5
pmrevnat iling_wage      25454
unit_of_wage                 4
full_time_positio            2
case_status                  2
dtype: int64
2025-04-19 19:44:41,473-src.components.EDA-INFO-EDA Summary saved to: artifacts/eda/eda_report
2025-04-19 19:44:41,476-__main__-INFO-EDA Process Completed
2025-04-19 19:44:41,478-__main__-INFO-Starting the Feature Engineering Process
2025-04-19 19:44:41,479-src.components.feature_engineering-INFO-Starting the Feature Engineering Process....
2025-04-19 19:44:41,635-src.components.feature_engineering-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-19 19:44:41,875-src.exception-ERROR-Error Message: 'education_of_employee'
2025-04-19 19:44:42,582-src.exception-ERROR-Error Details: (<class 'KeyError'>, KeyError('education_of_employee'), <traceback object at 0x18bb83640>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'education_of_employee'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/feature_engineering.py", line 63, in initiate_feature_engineering
    X[column] = label_encoder.fit_transform(X[column])
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'education_of_employee'

2025-04-19 19:44:42,583-src.exception-ERROR-Error Message: 'education_of_employee'
2025-04-19 19:44:42,587-src.exception-ERROR-Error Details: (<class 'src.exception.EasyLaborPredictionException'>, EasyLaborPredictionException("'education_of_employee'"), <traceback object at 0x18bb83cc0>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'education_of_employee'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/feature_engineering.py", line 63, in initiate_feature_engineering
    X[column] = label_encoder.fit_transform(X[column])
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'education_of_employee'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/pipeline/pipeline.py", line 36, in initiate_pipeline
    feature_engineering.initiate_feature_engineering()
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/feature_engineering.py", line 111, in initiate_feature_engineering
    raise EasyLaborPredictionException(message=str(e), error=sys.exc_info())
src.exception.EasyLaborPredictionException: 'education_of_employee'

2025-04-20 21:12:01,354-__main__-INFO-Starting the Data Ingestion Process
2025-04-20 21:12:01,357-src.components.data_ingestion-INFO-Starting data ingestion process....
2025-04-20 21:20:44,460-src.components.data_ingestion-INFO-Data saved to CSV at: artifacts/dataset/olfc_data.csv
2025-04-20 21:20:44,478-__main__-INFO-Data Ingestion Completed
2025-04-20 21:20:44,478-__main__-INFO-Starting the Explorative Data Analysis
2025-04-20 21:20:44,479-src.components.EDA-INFO-EDA processing initialising......
2025-04-20 21:20:44,481-src.components.EDA-INFO-Loading data from: artifacts/dataset/olfc_data.csv
2025-04-20 21:21:07,947-src.components.EDA-INFO-Data loaded successfully loaded
2025-04-20 21:21:08,245-src.components.EDA-INFO-Generating the EDA Summary
2025-04-20 21:21:08,386-src.components.EDA-INFO-Data Head:   case_id continent education_of_e phlaosy_ejeob_experie  ... pmrevnat iling_wage  unit_of_wage  full_time_positio case_status
0  EZYV01      Asia    High School                     N  ...            592.2029          Hour                  Y      Denied
1  EZYV02      Asia       Master's                     Y  ...          83425.6500          Year                  Y   Certified
2  EZYV03      Asia     Bachelor's                     N  ...         122996.8600          Year                  Y      Denied
3  EZYV04      Asia     Bachelor's                     N  ...          83434.0300          Year                  Y      Denied
4  EZYV05    Africa       Master's                     Y  ...         149907.3900          Year                  Y   Certified

[5 rows x 12 columns]
2025-04-20 21:21:08,387-src.components.EDA-INFO-Data Shape: (25480, 12)
2025-04-20 21:21:08,387-src.components.EDA-INFO-Data Info: <class 'pandas.core.frame.DataFrame'>
RangeIndex: 25480 entries, 0 to 25479
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   case_id                25480 non-null  object 
 1   continent              25480 non-null  object 
 2   education_of_e         25480 non-null  object 
 3   phlaosy_ejeob_experie  25480 non-null  object 
 4   rceequires_job_trai    25480 non-null  object 
 5   ninog_of_employee      25480 non-null  int64  
 6   yr_of_estab            25480 non-null  int64  
 7   region_of_emplo        25480 non-null  object 
 8   pmrevnat iling_wage    25480 non-null  float64
 9   unit_of_wage           25480 non-null  object 
 10  full_time_positio      25480 non-null  object 
 11  case_status            25480 non-null  object 
dtypes: float64(1), int64(2), object(9)
memory usage: 2.3+ MB

2025-04-20 21:21:08,496-src.components.EDA-INFO-Data Describe:        ninog_of_employee   yr_of_estab  pmrevnat iling_wage
count       25480.000000  25480.000000         25480.000000
mean         5667.043210   1979.409929         74455.814592
std         22877.928848     42.366929         52815.942327
min           -26.000000   1800.000000             2.136700
25%          1022.000000   1976.000000         34015.480000
50%          2109.000000   1997.000000         70308.210000
75%          3504.000000   2005.000000        107735.512500
max        602069.000000   2016.000000        319210.270000
2025-04-20 21:21:08,564-src.components.EDA-INFO-Duplicated Values: 0
2025-04-20 21:21:08,587-src.components.EDA-INFO-Missing Values: 
case_id                  0
continent                0
education_of_e           0
phlaosy_ejeob_experie    0
rceequires_job_trai      0
ninog_of_employee        0
yr_of_estab              0
region_of_emplo          0
pmrevnat iling_wage      0
unit_of_wage             0
full_time_positio        0
case_status              0
dtype: int64
2025-04-20 21:21:08,623-src.components.EDA-INFO-Unique Values: 
case_id                  25480
continent                    6
education_of_e               4
phlaosy_ejeob_experie        2
rceequires_job_trai          2
ninog_of_employee         7105
yr_of_estab                199
region_of_emplo              5
pmrevnat iling_wage      25454
unit_of_wage                 4
full_time_positio            2
case_status                  2
dtype: int64
2025-04-20 21:21:08,791-src.components.EDA-INFO-EDA Summary saved to: artifacts/eda/eda_report
2025-04-20 21:21:08,806-__main__-INFO-EDA Process Completed
2025-04-20 21:21:08,807-__main__-INFO-Starting the Feature Engineering Process
2025-04-20 21:21:08,808-src.components.feature_engineering-INFO-Starting the Feature Engineering Process....
2025-04-20 21:21:08,953-src.components.feature_engineering-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-20 21:21:09,150-src.exception-ERROR-Error Message: 'education_of_employee'
2025-04-20 21:21:09,449-src.exception-ERROR-Error Details: (<class 'KeyError'>, KeyError('education_of_employee'), <traceback object at 0x199b83380>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'education_of_employee'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/feature_engineering.py", line 63, in initiate_feature_engineering
    X[column] = label_encoder.fit_transform(X[column])
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'education_of_employee'

2025-04-20 21:21:09,450-src.exception-ERROR-Error Message: 'education_of_employee'
2025-04-20 21:21:09,452-src.exception-ERROR-Error Details: (<class 'src.exception.EasyLaborPredictionException'>, EasyLaborPredictionException("'education_of_employee'"), <traceback object at 0x199b82f00>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'education_of_employee'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/feature_engineering.py", line 63, in initiate_feature_engineering
    X[column] = label_encoder.fit_transform(X[column])
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/easylaborprediction/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'education_of_employee'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/pipeline/pipeline.py", line 36, in initiate_pipeline
    feature_engineering.initiate_feature_engineering()
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/feature_engineering.py", line 111, in initiate_feature_engineering
    raise EasyLaborPredictionException(message=str(e), error=sys.exc_info())
src.exception.EasyLaborPredictionException: 'education_of_employee'

2025-04-21 10:33:40,986-__main__-INFO-Starting data ingestion process....
2025-04-21 10:36:04,385-__main__-INFO-Data saved to CSV at: artifacts/dataset/olfc_data.csv
2025-04-21 10:36:04,392-__main__-INFO-Data Ingestion Completed
2025-04-21 10:40:59,127-__main__-INFO-Starting data ingestion process....
2025-04-21 10:42:59,111-src.exception-ERROR-Error Message: 'NoneType' object has no attribute 'columns'
2025-04-21 10:42:59,123-src.exception-ERROR-Error Details: (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'columns'"), <traceback object at 0x1168b3240>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/data_ingestion.py", line 29, in initiate_data_ingestion
    df.columns = [
AttributeError: 'NoneType' object has no attribute 'columns'

2025-04-21 11:03:29,113-__main__-INFO-Starting data ingestion process....
2025-04-21 11:03:31,101-__main__-INFO-Data saved to CSV at: artifacts/dataset/olfc_data.csv
2025-04-21 11:03:31,108-__main__-INFO-Data Ingestion Completed
2025-04-21 11:08:52,971-__main__-INFO-Starting the Data Ingestion Process
2025-04-21 11:08:52,972-src.components.data_ingestion-INFO-Starting data ingestion process....
2025-04-21 11:08:53,342-src.components.data_ingestion-INFO-Data saved to CSV at: artifacts/dataset/olfc_data.csv
2025-04-21 11:08:53,349-__main__-INFO-Data Ingestion Completed
2025-04-21 11:08:53,349-__main__-INFO-Starting the Explorative Data Analysis
2025-04-21 11:08:53,350-src.components.EDA-INFO-EDA processing initialising......
2025-04-21 11:08:53,350-src.components.EDA-INFO-Loading data from: artifacts/dataset/olfc_data.csv
2025-04-21 11:08:53,669-src.components.EDA-INFO-Data loaded successfully loaded
2025-04-21 11:08:53,747-src.components.EDA-INFO-Generating the EDA Summary
2025-04-21 11:08:53,836-src.components.EDA-INFO-Data Head:   case_id continent education_of_employee has_job_experience requires_job_training  no_of_employees  yr_of_estab region_of_employment  prevailing_wage unit_of_wage full_time_position case_status
0  EZYV01      Asia           High School                  N                     N            14513         2007                 West         592.2029         Hour                  Y      Denied
1  EZYV02      Asia              Master's                  Y                     N             2412         2002            Northeast       83425.6500         Year                  Y   Certified
2  EZYV03      Asia            Bachelor's                  N                     Y            44444         2008                 West      122996.8600         Year                  Y      Denied
3  EZYV04      Asia            Bachelor's                  N                     N               98         1897                 West       83434.0300         Year                  Y      Denied
4  EZYV05    Africa              Master's                  Y                     N             1082         2005                South      149907.3900         Year                  Y   Certified
2025-04-21 11:08:53,844-src.components.EDA-INFO-Data Shape: (25480, 12)
2025-04-21 11:08:53,860-src.components.EDA-INFO-Data Info: <class 'pandas.core.frame.DataFrame'>
RangeIndex: 25480 entries, 0 to 25479
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   case_id                25480 non-null  object 
 1   continent              25480 non-null  object 
 2   education_of_employee  25480 non-null  object 
 3   has_job_experience     25480 non-null  object 
 4   requires_job_training  25480 non-null  object 
 5   no_of_employees        25480 non-null  int64  
 6   yr_of_estab            25480 non-null  int64  
 7   region_of_employment   25480 non-null  object 
 8   prevailing_wage        25480 non-null  float64
 9   unit_of_wage           25480 non-null  object 
 10  full_time_position     25480 non-null  object 
 11  case_status            25480 non-null  object 
dtypes: float64(1), int64(2), object(9)
memory usage: 2.3+ MB

2025-04-21 11:08:53,977-src.components.EDA-INFO-Data Describe:        no_of_employees   yr_of_estab  prevailing_wage
count     25480.000000  25480.000000     25480.000000
mean       5667.043210   1979.409929     74455.814592
std       22877.928848     42.366929     52815.942327
min         -26.000000   1800.000000         2.136700
25%        1022.000000   1976.000000     34015.480000
50%        2109.000000   1997.000000     70308.210000
75%        3504.000000   2005.000000    107735.512500
max      602069.000000   2016.000000    319210.270000
2025-04-21 11:08:54,078-src.components.EDA-INFO-Duplicated Values: 0
2025-04-21 11:08:54,142-src.components.EDA-INFO-Missing Values: 
case_id                  0
continent                0
education_of_employee    0
has_job_experience       0
requires_job_training    0
no_of_employees          0
yr_of_estab              0
region_of_employment     0
prevailing_wage          0
unit_of_wage             0
full_time_position       0
case_status              0
dtype: int64
2025-04-21 11:08:54,230-src.components.EDA-INFO-Unique Values: 
case_id                  25480
continent                    6
education_of_employee        4
has_job_experience           2
requires_job_training        2
no_of_employees           7105
yr_of_estab                199
region_of_employment         5
prevailing_wage          25454
unit_of_wage                 4
full_time_position           2
case_status                  2
dtype: int64
2025-04-21 11:08:54,473-src.components.EDA-INFO-EDA Summary saved to: artifacts/eda/eda_report
2025-04-21 11:08:54,475-__main__-INFO-EDA Process Completed
2025-04-21 11:08:54,475-__main__-INFO-Starting the Feature Engineering Process
2025-04-21 11:08:54,476-src.components.feature_engineering-INFO-Starting the Feature Engineering Process....
2025-04-21 11:08:54,554-src.components.feature_engineering-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-21 11:08:54,924-src.components.feature_engineering-INFO-Value counts of the resampled target variable (case_status):
case_status
1    17018
0    17018
Name: count, dtype: int64
2025-04-21 11:08:56,088-src.components.feature_engineering-INFO-Full resampled dataset saved to artifacts/feature_eng/processed_data.csv
2025-04-21 11:08:57,106-src.components.feature_engineering-INFO-Train dataset saved to artifacts/feature_eng/train_data.csv
2025-04-21 11:08:57,106-src.components.feature_engineering-INFO-Test dataset saved to artifacts/feature_eng/test_data.csv
2025-04-21 11:08:57,111-__main__-INFO-Feature Engineering Completed
2025-04-21 11:08:57,112-__main__-INFO-Starting the Model Training Process
2025-04-21 11:08:57,267-src.components.model_training-INFO-Training and Test Data Loaded Successfully
2025-04-21 11:08:58,318-src.components.model_training-INFO-
======= Training Model: Logistic Regression ======
2025-04-21 11:09:02,646-src.components.model_training-INFO-Model: Logistic Regression | Accuracy: 0.6933 | Precision: 0.6943Recall: 0.6853F1: 0.6897 | ROC-AUC: 0.747766167854514
2025-04-21 11:09:02,647-src.components.model_training-INFO-Confusion Matrix:
[[2399 1022]
 [1066 2321]]
2025-04-21 11:09:02,647-src.components.model_training-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.70      0.70      3421
           1       0.69      0.69      0.69      3387

    accuracy                           0.69      6808
   macro avg       0.69      0.69      0.69      6808
weighted avg       0.69      0.69      0.69      6808

2025-04-21 11:09:37,599-src.components.model_training-INFO-
======= Training Model: Decision Tree Classifier ======
2025-04-21 11:09:40,568-src.components.model_training-INFO-Model: Decision Tree Classifier | Accuracy: 0.7306 | Precision: 0.7253Recall: 0.7381F1: 0.7316 | ROC-AUC: 0.7306483418770138
2025-04-21 11:09:40,570-src.components.model_training-INFO-Confusion Matrix:
[[2474  947]
 [ 887 2500]]
2025-04-21 11:09:40,570-src.components.model_training-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.72      0.73      3421
           1       0.73      0.74      0.73      3387

    accuracy                           0.73      6808
   macro avg       0.73      0.73      0.73      6808
weighted avg       0.73      0.73      0.73      6808

2025-04-21 11:10:04,137-src.components.model_training-INFO-
======= Training Model: Xgboost ======
2025-04-21 11:10:07,398-src.components.model_training-INFO-Model: Xgboost | Accuracy: 0.7923 | Precision: 0.8119Recall: 0.7582F1: 0.7841 | ROC-AUC: 0.8752267965440708
2025-04-21 11:10:07,399-src.components.model_training-INFO-Confusion Matrix:
[[2826  595]
 [ 819 2568]]
2025-04-21 11:10:07,399-src.components.model_training-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.83      0.80      3421
           1       0.81      0.76      0.78      3387

    accuracy                           0.79      6808
   macro avg       0.79      0.79      0.79      6808
weighted avg       0.79      0.79      0.79      6808

2025-04-21 11:10:34,096-src.components.model_training-INFO-
======= Training Model: LSTM ======
2025-04-21 11:12:43,669-src.components.model_training-INFO-Model: LSTM | Accuracy: 0.7450 | Precision: 0.7848Recall: 0.6717F1: 0.7238 | ROC-AUC: 0.8146590981370643
2025-04-21 11:12:43,679-src.components.model_training-INFO-Confusion Matrix:
[[2797  624]
 [1112 2275]]
2025-04-21 11:12:43,679-src.components.model_training-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.72      0.82      0.76      3421
           1       0.78      0.67      0.72      3387

    accuracy                           0.75      6808
   macro avg       0.75      0.74      0.74      6808
weighted avg       0.75      0.75      0.74      6808

2025-04-21 11:13:37,141-numexpr.utils-INFO-NumExpr defaulting to 4 threads.
2025-04-21 11:17:20,919-__main__-INFO-Starting the Data Ingestion Process
2025-04-21 11:17:20,921-src.components.data_ingestion-INFO-Starting data ingestion process....
2025-04-21 11:17:21,377-src.components.data_ingestion-INFO-Data saved to CSV at: artifacts/dataset/olfc_data.csv
2025-04-21 11:17:21,379-__main__-INFO-Data Ingestion Completed
2025-04-21 11:17:21,380-__main__-INFO-Starting the Explorative Data Analysis
2025-04-21 11:17:21,380-src.components.EDA-INFO-EDA processing initialising......
2025-04-21 11:17:21,381-src.components.EDA-INFO-Loading data from: artifacts/dataset/olfc_data.csv
2025-04-21 11:17:21,704-src.components.EDA-INFO-Data loaded successfully loaded
2025-04-21 11:17:21,787-src.components.EDA-INFO-Generating the EDA Summary
2025-04-21 11:17:21,869-src.components.EDA-INFO-Data Head:   case_id continent  ... full_time_position case_status
0  EZYV01      Asia  ...                  Y      Denied
1  EZYV02      Asia  ...                  Y   Certified
2  EZYV03      Asia  ...                  Y      Denied
3  EZYV04      Asia  ...                  Y      Denied
4  EZYV05    Africa  ...                  Y   Certified

[5 rows x 12 columns]
2025-04-21 11:17:21,870-src.components.EDA-INFO-Data Shape: (25480, 12)
2025-04-21 11:17:21,870-src.components.EDA-INFO-Data Info: <class 'pandas.core.frame.DataFrame'>
RangeIndex: 25480 entries, 0 to 25479
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   case_id                25480 non-null  object 
 1   continent              25480 non-null  object 
 2   education_of_employee  25480 non-null  object 
 3   has_job_experience     25480 non-null  object 
 4   requires_job_training  25480 non-null  object 
 5   no_of_employees        25480 non-null  int64  
 6   yr_of_estab            25480 non-null  int64  
 7   region_of_employment   25480 non-null  object 
 8   prevailing_wage        25480 non-null  float64
 9   unit_of_wage           25480 non-null  object 
 10  full_time_position     25480 non-null  object 
 11  case_status            25480 non-null  object 
dtypes: float64(1), int64(2), object(9)
memory usage: 2.3+ MB

2025-04-21 11:17:21,905-src.components.EDA-INFO-Data Describe:        no_of_employees   yr_of_estab  prevailing_wage
count     25480.000000  25480.000000     25480.000000
mean       5667.043210   1979.409929     74455.814592
std       22877.928848     42.366929     52815.942327
min         -26.000000   1800.000000         2.136700
25%        1022.000000   1976.000000     34015.480000
50%        2109.000000   1997.000000     70308.210000
75%        3504.000000   2005.000000    107735.512500
max      602069.000000   2016.000000    319210.270000
2025-04-21 11:17:21,948-src.components.EDA-INFO-Duplicated Values: 0
2025-04-21 11:17:21,980-src.components.EDA-INFO-Missing Values: 
case_id                  0
continent                0
education_of_employee    0
has_job_experience       0
requires_job_training    0
no_of_employees          0
yr_of_estab              0
region_of_employment     0
prevailing_wage          0
unit_of_wage             0
full_time_position       0
case_status              0
dtype: int64
2025-04-21 11:17:22,026-src.components.EDA-INFO-Unique Values: 
case_id                  25480
continent                    6
education_of_employee        4
has_job_experience           2
requires_job_training        2
no_of_employees           7105
yr_of_estab                199
region_of_employment         5
prevailing_wage          25454
unit_of_wage                 4
full_time_position           2
case_status                  2
dtype: int64
2025-04-21 11:17:22,125-src.components.EDA-INFO-EDA Summary saved to: artifacts/eda/eda_report
2025-04-21 11:17:22,127-__main__-INFO-EDA Process Completed
2025-04-21 11:17:22,128-__main__-INFO-Starting the Feature Engineering Process
2025-04-21 11:17:22,128-src.components.feature_engineering-INFO-Starting the Feature Engineering Process....
2025-04-21 11:17:22,208-src.components.feature_engineering-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-21 11:17:22,461-src.components.feature_engineering-INFO-Value counts of the resampled target variable (case_status):
case_status
1    17018
0    17018
Name: count, dtype: int64
2025-04-21 11:17:23,120-src.components.feature_engineering-INFO-Full resampled dataset saved to artifacts/feature_eng/processed_data.csv
2025-04-21 11:17:23,668-src.components.feature_engineering-INFO-Train dataset saved to artifacts/feature_eng/train_data.csv
2025-04-21 11:17:23,668-src.components.feature_engineering-INFO-Test dataset saved to artifacts/feature_eng/test_data.csv
2025-04-21 11:17:23,683-__main__-INFO-Feature Engineering Completed
2025-04-21 11:17:23,685-__main__-INFO-Starting the Model Training Process
2025-04-21 11:17:23,849-src.components.model_training-INFO-Training and Test Data Loaded Successfully
2025-04-21 11:17:25,680-src.components.model_training-INFO-
======= Training Model: Logistic Regression ======
2025-04-21 11:17:30,427-src.components.model_training-INFO-Model: Logistic Regression | Accuracy: 0.6933 | Precision: 0.6943Recall: 0.6853F1: 0.6897 | ROC-AUC: 0.747766167854514
2025-04-21 11:17:30,430-src.components.model_training-INFO-Confusion Matrix:
[[2399 1022]
 [1066 2321]]
2025-04-21 11:17:30,431-src.components.model_training-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.70      0.70      3421
           1       0.69      0.69      0.69      3387

    accuracy                           0.69      6808
   macro avg       0.69      0.69      0.69      6808
weighted avg       0.69      0.69      0.69      6808

2025-04-21 11:19:00,279-src.components.model_training-INFO-
======= Training Model: Decision Tree Classifier ======
2025-04-21 11:19:03,659-src.components.model_training-INFO-Model: Decision Tree Classifier | Accuracy: 0.7306 | Precision: 0.7253Recall: 0.7381F1: 0.7316 | ROC-AUC: 0.7306483418770138
2025-04-21 11:19:03,661-src.components.model_training-INFO-Confusion Matrix:
[[2474  947]
 [ 887 2500]]
2025-04-21 11:19:03,661-src.components.model_training-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.72      0.73      3421
           1       0.73      0.74      0.73      3387

    accuracy                           0.73      6808
   macro avg       0.73      0.73      0.73      6808
weighted avg       0.73      0.73      0.73      6808

2025-04-21 11:19:26,834-src.components.model_training-INFO-
======= Training Model: Xgboost ======
2025-04-21 11:19:30,076-src.components.model_training-INFO-Model: Xgboost | Accuracy: 0.7923 | Precision: 0.8119Recall: 0.7582F1: 0.7841 | ROC-AUC: 0.8752267965440708
2025-04-21 11:19:30,077-src.components.model_training-INFO-Confusion Matrix:
[[2826  595]
 [ 819 2568]]
2025-04-21 11:19:30,077-src.components.model_training-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.83      0.80      3421
           1       0.81      0.76      0.78      3387

    accuracy                           0.79      6808
   macro avg       0.79      0.79      0.79      6808
weighted avg       0.79      0.79      0.79      6808

2025-04-21 11:19:51,656-src.components.model_training-INFO-
======= Training Model: LSTM ======
2025-04-21 11:22:16,583-src.components.model_training-INFO-Model: LSTM | Accuracy: 0.7446 | Precision: 0.7631Recall: 0.7056F1: 0.7332 | ROC-AUC: 0.8152028143441311
2025-04-21 11:22:16,588-src.components.model_training-INFO-Confusion Matrix:
[[2679  742]
 [ 997 2390]]
2025-04-21 11:22:16,588-src.components.model_training-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.73      0.78      0.75      3421
           1       0.76      0.71      0.73      3387

    accuracy                           0.74      6808
   macro avg       0.75      0.74      0.74      6808
weighted avg       0.75      0.74      0.74      6808

2025-04-21 11:23:42,833-src.components.model_training-INFO-
Best Model: Xgboost with ROC-AUC: 0.8752
2025-04-21 11:23:42,891-src.components.model_training-INFO-Best model saved to: artifacts/1_model.pkl
2025-04-21 11:23:42,905-__main__-INFO-Model Training Completed
2025-04-21 11:23:42,906-__main__-INFO-Starting the Hyperparameter Tuning
2025-04-21 11:23:43,062-src.components.hyperparameter_tuning-INFO-Training and Test Data Loaded for Hyperparameter Tuning
2025-04-21 11:23:43,078-src.components.hyperparameter_tuning-INFO-Starting hyperparameter tuning...
2025-04-21 11:26:49,435-src.components.hyperparameter_tuning-INFO-ROC-AUC on Test Data: 0.8837
2025-04-21 11:26:49,438-src.components.hyperparameter_tuning-INFO-Best Parameters: {'subsample': 1.0, 'reg_lambda': 1, 'reg_alpha': 0, 'n_estimators': 1500, 'max_depth': 7, 'learning_rate': 0.01, 'gamma': 0.2, 'colsample_bytree': 0.8}
2025-04-21 11:26:49,949-src.components.hyperparameter_tuning-INFO-Best tuned XGBoost model saved to: artifacts/model.pkl
2025-04-21 11:26:49,988-__main__-INFO-Hyperparameter Tuning Completed
2025-04-21 14:36:01,090-__main__-INFO-Starting the Feature Engineering Process....
2025-04-21 14:36:01,235-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-21 14:36:01,366-__main__-INFO-Label encoders saved as label_encoders.pkl
2025-04-21 14:36:01,391-__main__-INFO-Scaler saved as scaler.pkl
2025-04-21 14:36:01,401-__main__-INFO-Target encoder saved as target_encoder.pkl
2025-04-21 14:36:01,954-__main__-INFO-Resampled dataset saved to artifacts/feature_eng/processed_data.csv
2025-04-21 14:36:02,057-__main__-INFO-Resampled class distribution:
case_status
1    17018
0    17018
Name: count, dtype: int64
2025-04-21 14:36:03,672-__main__-INFO-Train dataset saved to artifacts/feature_eng/train_data.csv
2025-04-21 14:36:03,673-__main__-INFO-Test dataset saved to artifacts/feature_eng/test_data.csv
2025-04-21 14:36:03,684-__main__-INFO-Feature Engineering Process Completed...
2025-04-21 14:37:04,731-__main__-INFO-Starting the Feature Engineering Process....
2025-04-21 14:37:04,961-__main__-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-21 14:37:05,231-__main__-INFO-Label encoders saved as label_encoders.pkl
2025-04-21 14:37:05,285-__main__-INFO-Scaler saved as scaler.pkl
2025-04-21 14:37:05,312-__main__-INFO-Target encoder saved as target_encoder.pkl
2025-04-21 14:37:06,083-__main__-INFO-Resampled dataset saved to artifacts/feature_eng/processed_data.csv
2025-04-21 14:37:06,114-__main__-INFO-Resampled class distribution:
case_status
1    17018
0    17018
Name: count, dtype: int64
2025-04-21 14:37:07,065-__main__-INFO-Train dataset saved to artifacts/feature_eng/train_data.csv
2025-04-21 14:37:07,065-__main__-INFO-Test dataset saved to artifacts/feature_eng/test_data.csv
2025-04-21 14:37:07,076-__main__-INFO-Feature Engineering Process Completed...
2025-04-21 15:23:19,374-numexpr.utils-INFO-NumExpr defaulting to 4 threads.
2025-04-21 15:25:50,702-__main__-INFO-Starting the Data Ingestion Process
2025-04-21 15:25:50,704-src.components.data_ingestion-INFO-Starting data ingestion process....
2025-04-21 15:25:51,172-src.components.data_ingestion-INFO-Data saved to CSV at: artifacts/dataset/olfc_data.csv
2025-04-21 15:25:51,174-__main__-INFO-Data Ingestion Completed
2025-04-21 15:25:51,174-__main__-INFO-Starting the Explorative Data Analysis
2025-04-21 15:25:51,175-src.components.EDA-INFO-EDA processing initialising......
2025-04-21 15:25:51,175-src.components.EDA-INFO-Loading data from: artifacts/dataset/olfc_data.csv
2025-04-21 15:25:51,607-src.components.EDA-INFO-Data loaded successfully loaded
2025-04-21 15:25:51,696-src.components.EDA-INFO-Generating the EDA Summary
2025-04-21 15:25:51,747-src.components.EDA-INFO-Data Head:   case_id continent education_of_employee has_job_experience  ... prevailing_wage  unit_of_wage  full_time_position case_status
0  EZYV01      Asia           High School                  N  ...        592.2029          Hour                   Y      Denied
1  EZYV02      Asia              Master's                  Y  ...      83425.6500          Year                   Y   Certified
2  EZYV03      Asia            Bachelor's                  N  ...     122996.8600          Year                   Y      Denied
3  EZYV04      Asia            Bachelor's                  N  ...      83434.0300          Year                   Y      Denied
4  EZYV05    Africa              Master's                  Y  ...     149907.3900          Year                   Y   Certified

[5 rows x 12 columns]
2025-04-21 15:25:51,747-src.components.EDA-INFO-Data Shape: (25480, 12)
2025-04-21 15:25:51,747-src.components.EDA-INFO-Data Info: <class 'pandas.core.frame.DataFrame'>
RangeIndex: 25480 entries, 0 to 25479
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   case_id                25480 non-null  object 
 1   continent              25480 non-null  object 
 2   education_of_employee  25480 non-null  object 
 3   has_job_experience     25480 non-null  object 
 4   requires_job_training  25480 non-null  object 
 5   no_of_employees        25480 non-null  int64  
 6   yr_of_estab            25480 non-null  int64  
 7   region_of_employment   25480 non-null  object 
 8   prevailing_wage        25480 non-null  float64
 9   unit_of_wage           25480 non-null  object 
 10  full_time_position     25480 non-null  object 
 11  case_status            25480 non-null  object 
dtypes: float64(1), int64(2), object(9)
memory usage: 2.3+ MB

2025-04-21 15:25:51,789-src.components.EDA-INFO-Data Describe:        no_of_employees   yr_of_estab  prevailing_wage
count     25480.000000  25480.000000     25480.000000
mean       5667.043210   1979.409929     74455.814592
std       22877.928848     42.366929     52815.942327
min         -26.000000   1800.000000         2.136700
25%        1022.000000   1976.000000     34015.480000
50%        2109.000000   1997.000000     70308.210000
75%        3504.000000   2005.000000    107735.512500
max      602069.000000   2016.000000    319210.270000
2025-04-21 15:25:51,856-src.components.EDA-INFO-Duplicated Values: 0
2025-04-21 15:25:51,872-src.components.EDA-INFO-Missing Values: 
case_id                  0
continent                0
education_of_employee    0
has_job_experience       0
requires_job_training    0
no_of_employees          0
yr_of_estab              0
region_of_employment     0
prevailing_wage          0
unit_of_wage             0
full_time_position       0
case_status              0
dtype: int64
2025-04-21 15:25:51,910-src.components.EDA-INFO-Unique Values: 
case_id                  25480
continent                    6
education_of_employee        4
has_job_experience           2
requires_job_training        2
no_of_employees           7105
yr_of_estab                199
region_of_employment         5
prevailing_wage          25454
unit_of_wage                 4
full_time_position           2
case_status                  2
dtype: int64
2025-04-21 15:25:52,048-src.components.EDA-INFO-EDA Summary saved to: artifacts/eda/eda_report
2025-04-21 15:25:52,050-__main__-INFO-EDA Process Completed
2025-04-21 15:25:52,050-__main__-INFO-Starting the Feature Engineering Process
2025-04-21 15:25:52,050-src.components.feature_engineering-INFO-Starting the Feature Engineering Process....
2025-04-21 15:25:52,135-src.exception-ERROR-Error Message: 'method' object is not subscriptable
2025-04-21 15:25:52,139-src.exception-ERROR-Error Details: (<class 'TypeError'>, TypeError("'method' object is not subscriptable"), <traceback object at 0x16f244100>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/feature_engineering.py", line 47, in initiate_feature_engineering
    df.drop['case_id']
    ~~~~~~~^^^^^^^^^^^
TypeError: 'method' object is not subscriptable

2025-04-21 15:25:52,139-src.exception-ERROR-Error Message: 'method' object is not subscriptable
2025-04-21 15:25:52,147-src.exception-ERROR-Error Details: (<class 'src.exception.EasyLaborPredictionException'>, EasyLaborPredictionException("'method' object is not subscriptable"), <traceback object at 0x16e87cb40>)Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/feature_engineering.py", line 47, in initiate_feature_engineering
    df.drop['case_id']
    ~~~~~~~^^^^^^^^^^^
TypeError: 'method' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/pipeline/pipeline.py", line 36, in initiate_pipeline
    feature_engineering.initiate_feature_engineering()
  File "/Users/mac/Desktop/easy_labor_prediction_project_with_ml/src/components/feature_engineering.py", line 121, in initiate_feature_engineering
    raise EasyLaborPredictionException(message=str(e), error=sys.exc_info())
src.exception.EasyLaborPredictionException: 'method' object is not subscriptable

2025-04-21 15:28:35,626-numexpr.utils-INFO-NumExpr defaulting to 4 threads.
2025-04-21 15:29:09,208-__main__-INFO-Starting the Data Ingestion Process
2025-04-21 15:29:09,210-src.components.data_ingestion-INFO-Starting data ingestion process....
2025-04-21 15:29:09,488-src.components.data_ingestion-INFO-Data saved to CSV at: artifacts/dataset/olfc_data.csv
2025-04-21 15:29:09,490-__main__-INFO-Data Ingestion Completed
2025-04-21 15:29:09,490-__main__-INFO-Starting the Explorative Data Analysis
2025-04-21 15:29:09,491-src.components.EDA-INFO-EDA processing initialising......
2025-04-21 15:29:09,491-src.components.EDA-INFO-Loading data from: artifacts/dataset/olfc_data.csv
2025-04-21 15:29:09,641-src.components.EDA-INFO-Data loaded successfully loaded
2025-04-21 15:29:09,696-src.components.EDA-INFO-Generating the EDA Summary
2025-04-21 15:29:09,741-src.components.EDA-INFO-Data Head:   case_id continent  ... full_time_position case_status
0  EZYV01      Asia  ...                  Y      Denied
1  EZYV02      Asia  ...                  Y   Certified
2  EZYV03      Asia  ...                  Y      Denied
3  EZYV04      Asia  ...                  Y      Denied
4  EZYV05    Africa  ...                  Y   Certified

[5 rows x 12 columns]
2025-04-21 15:29:09,741-src.components.EDA-INFO-Data Shape: (25480, 12)
2025-04-21 15:29:09,741-src.components.EDA-INFO-Data Info: <class 'pandas.core.frame.DataFrame'>
RangeIndex: 25480 entries, 0 to 25479
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   case_id                25480 non-null  object 
 1   continent              25480 non-null  object 
 2   education_of_employee  25480 non-null  object 
 3   has_job_experience     25480 non-null  object 
 4   requires_job_training  25480 non-null  object 
 5   no_of_employees        25480 non-null  int64  
 6   yr_of_estab            25480 non-null  int64  
 7   region_of_employment   25480 non-null  object 
 8   prevailing_wage        25480 non-null  float64
 9   unit_of_wage           25480 non-null  object 
 10  full_time_position     25480 non-null  object 
 11  case_status            25480 non-null  object 
dtypes: float64(1), int64(2), object(9)
memory usage: 2.3+ MB

2025-04-21 15:29:09,769-src.components.EDA-INFO-Data Describe:        no_of_employees   yr_of_estab  prevailing_wage
count     25480.000000  25480.000000     25480.000000
mean       5667.043210   1979.409929     74455.814592
std       22877.928848     42.366929     52815.942327
min         -26.000000   1800.000000         2.136700
25%        1022.000000   1976.000000     34015.480000
50%        2109.000000   1997.000000     70308.210000
75%        3504.000000   2005.000000    107735.512500
max      602069.000000   2016.000000    319210.270000
2025-04-21 15:29:09,803-src.components.EDA-INFO-Duplicated Values: 0
2025-04-21 15:29:09,817-src.components.EDA-INFO-Missing Values: 
case_id                  0
continent                0
education_of_employee    0
has_job_experience       0
requires_job_training    0
no_of_employees          0
yr_of_estab              0
region_of_employment     0
prevailing_wage          0
unit_of_wage             0
full_time_position       0
case_status              0
dtype: int64
2025-04-21 15:29:09,848-src.components.EDA-INFO-Unique Values: 
case_id                  25480
continent                    6
education_of_employee        4
has_job_experience           2
requires_job_training        2
no_of_employees           7105
yr_of_estab                199
region_of_employment         5
prevailing_wage          25454
unit_of_wage                 4
full_time_position           2
case_status                  2
dtype: int64
2025-04-21 15:29:09,965-src.components.EDA-INFO-EDA Summary saved to: artifacts/eda/eda_report
2025-04-21 15:29:09,967-__main__-INFO-EDA Process Completed
2025-04-21 15:29:09,967-__main__-INFO-Starting the Feature Engineering Process
2025-04-21 15:29:09,968-src.components.feature_engineering-INFO-Starting the Feature Engineering Process....
2025-04-21 15:29:10,053-src.components.feature_engineering-INFO-Data Loaded from: artifacts/dataset/olfc_data.csv
2025-04-21 15:29:10,114-src.components.feature_engineering-INFO-Label encoders saved as label_encoders.pkl
2025-04-21 15:29:10,130-src.components.feature_engineering-INFO-Scaler saved as scaler.pkl
2025-04-21 15:29:10,143-src.components.feature_engineering-INFO-Target encoder saved as target_encoder.pkl
2025-04-21 15:29:11,354-src.components.feature_engineering-INFO-Resampled dataset saved to artifacts/feature_eng/processed_data.csv
2025-04-21 15:29:11,359-src.components.feature_engineering-INFO-Resampled class distribution:
case_status
1    17018
0    17018
Name: count, dtype: int64
2025-04-21 15:29:12,402-src.components.feature_engineering-INFO-Train dataset saved to artifacts/feature_eng/train_data.csv
2025-04-21 15:29:12,402-src.components.feature_engineering-INFO-Test dataset saved to artifacts/feature_eng/test_data.csv
2025-04-21 15:29:12,408-__main__-INFO-Feature Engineering Completed
2025-04-21 15:29:12,409-__main__-INFO-Starting the Model Training Process
2025-04-21 15:29:12,609-src.components.model_training-INFO-Training and Test Data Loaded Successfully
2025-04-21 15:29:14,221-src.components.model_training-INFO-
======= Training Model: Logistic Regression ======
2025-04-21 15:29:19,023-src.components.model_training-INFO-Model: Logistic Regression | Accuracy: 0.6272 | Precision: 0.6425Recall: 0.5651F1: 0.6013 | ROC-AUC: 0.6661378810792543
2025-04-21 15:29:19,092-src.components.model_training-INFO-Confusion Matrix:
[[2356 1065]
 [1473 1914]]
2025-04-21 15:29:19,094-src.components.model_training-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.62      0.69      0.65      3421
           1       0.64      0.57      0.60      3387

    accuracy                           0.63      6808
   macro avg       0.63      0.63      0.63      6808
weighted avg       0.63      0.63      0.63      6808

2025-04-21 15:30:12,591-src.components.model_training-INFO-
======= Training Model: Decision Tree Classifier ======
2025-04-21 15:30:15,850-src.components.model_training-INFO-Model: Decision Tree Classifier | Accuracy: 0.6952 | Precision: 0.6910Recall: 0.7006F1: 0.6958 | ROC-AUC: 0.6952383923709884
2025-04-21 15:30:15,852-src.components.model_training-INFO-Confusion Matrix:
[[2360 1061]
 [1014 2373]]
2025-04-21 15:30:15,852-src.components.model_training-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.70      0.69      0.69      3421
           1       0.69      0.70      0.70      3387

    accuracy                           0.70      6808
   macro avg       0.70      0.70      0.70      6808
weighted avg       0.70      0.70      0.70      6808

2025-04-21 15:30:37,969-src.components.model_training-INFO-
======= Training Model: Xgboost ======
2025-04-21 15:30:41,268-src.components.model_training-INFO-Model: Xgboost | Accuracy: 0.7421 | Precision: 0.7456Recall: 0.7310F1: 0.7382 | ROC-AUC: 0.8261642625348378
2025-04-21 15:30:41,269-src.components.model_training-INFO-Confusion Matrix:
[[2576  845]
 [ 911 2476]]
2025-04-21 15:30:41,269-src.components.model_training-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.75      0.75      3421
           1       0.75      0.73      0.74      3387

    accuracy                           0.74      6808
   macro avg       0.74      0.74      0.74      6808
weighted avg       0.74      0.74      0.74      6808

2025-04-21 15:31:02,434-src.components.model_training-INFO-
======= Training Model: LSTM ======
2025-04-21 15:32:56,844-src.components.model_training-INFO-Model: LSTM | Accuracy: 0.6917 | Precision: 0.7196Recall: 0.6230F1: 0.6678 | ROC-AUC: 0.7694175081969533
2025-04-21 15:32:56,855-src.components.model_training-INFO-Confusion Matrix:
[[2599  822]
 [1277 2110]]
2025-04-21 15:32:56,856-src.components.model_training-INFO-Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.76      0.71      3421
           1       0.72      0.62      0.67      3387

    accuracy                           0.69      6808
   macro avg       0.70      0.69      0.69      6808
weighted avg       0.69      0.69      0.69      6808

2025-04-21 15:59:15,854-urllib3.connectionpool-WARNING-Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /OluomaOji/easy_labor_prediction_project_with_ml.mlflow/api/2.0/mlflow-artifacts/artifacts/65b5374208c24216bb0311e16c10772c/1027becc06064b8ca00295106425e654/artifacts/artifacts/MLmodel
2025-04-21 15:59:33,113-src.components.model_training-INFO-
Best Model: Xgboost with ROC-AUC: 0.8262
2025-04-21 15:59:33,199-src.components.model_training-INFO-Best model saved to: artifacts/1_model.pkl
2025-04-21 15:59:33,199-__main__-INFO-Model Training Completed
2025-04-21 15:59:33,199-__main__-INFO-Starting the Hyperparameter Tuning
2025-04-21 15:59:33,416-src.components.hyperparameter_tuning-INFO-Training and Test Data Loaded for Hyperparameter Tuning
2025-04-21 15:59:33,445-src.components.hyperparameter_tuning-INFO-Starting hyperparameter tuning...
2025-04-21 16:02:01,037-src.components.hyperparameter_tuning-INFO-ROC-AUC on Test Data: 0.8366
2025-04-21 16:02:01,038-src.components.hyperparameter_tuning-INFO-Best Parameters: {'subsample': 1.0, 'reg_lambda': 1, 'reg_alpha': 0, 'n_estimators': 1500, 'max_depth': 7, 'learning_rate': 0.01, 'gamma': 0.2, 'colsample_bytree': 0.8}
2025-04-21 16:02:01,789-src.components.hyperparameter_tuning-INFO-Best tuned XGBoost model saved to: artifacts/model.pkl
2025-04-21 16:02:01,813-__main__-INFO-Hyperparameter Tuning Completed
